# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Render the auth entity's two Source QML bridges.

Setting ``identity.provider_entity`` promotes identity out of the web edge and into an
entity of its own, which then owns two connect points: ``identity`` (the OAuth engine that
holds the client secret, runs the token exchange and keeps the tokens) and ``sessions`` (the
authoritative session store every edge reads through). Both need an owner-side Source, and
both Sources are the same in every project: they forward each slot to a C++ engine the
generated ``main.cpp`` puts in their context, and forward its answers back out as signals.

That is why they are generated rather than asked for. The docs promise promoting identity
is one line of configuration, so the files that line implies are emitted here, next to the
generated ``main.cpp`` that supplies their context objects.

The emitted text is fixed (nothing about it varies per project), and it is checked in at
``tests/m8-auth/auth/`` as that suite's fixture, so the M8 acceptance test drives exactly
this code over a real mesh link. A unit test compares the two, so the bridge that is proven
and the bridge that is generated cannot drift apart.
"""

from __future__ import annotations

_HEADER_QML = ("// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux\n"
               "// SPDX-License-Identifier: Apache-2.0\n")


IDENTITY_SOURCE_QML = _HEADER_QML + """
import QtQuick
import SynQt

// The authoritative identity Source on the auth entity (one instance per consuming
// edge, so each edge's answer reaches only that edge). It bridges the connect
// point to a single shared IdentityService (the `IdentityEngine` context object), which owns
// the client secret, the token exchange and the stored tokens. The service methods are
// synchronous, so this Source emits each result on itself and answers only the edge that
// asked; a user's identity never crosses to another edge.
//
// Generated by `synqt build` from `identity.provider_entity`; edit the topology, not this
// file.
Identity {
    id: root

    function beginLogin(requestId, provider, redirectUri, binding, context) {
        const result = IdentityEngine.beginLogin(provider, redirectUri, binding, context);
        root.emitBeginResult(requestId, result.state, result.authorizeUrl, result.error);
    }

    // The binding an edge tied this login to is held here with the state and checked here,
    // before the code is spent, so any edge process can answer a callback any other one
    // started and none of them can answer it twice.
    function exchangeCode(requestId, state, code, redirectUri, presentedBinding) {
        const result = IdentityEngine.exchangeCode(state, code, redirectUri, presentedBinding);
        root.emitExchangeResult(requestId, result.identityJson, result.context, result.error);
    }

    function bindSession(state, sessionId) {
        IdentityEngine.bindSession(state, sessionId);
    }

    // A desktop claim is minted on whichever edge answered the callback and redeemed over a
    // connection the native client opens for itself, so it is held here where every edge
    // can reach it. An empty sessionId is every failure alike, on purpose.
    function holdClaim(code, sessionId, challenge) {
        IdentityEngine.holdClaim(code, sessionId, challenge);
    }

    function takeClaim(requestId, code, verifier) {
        root.emitClaimResult(requestId, IdentityEngine.takeClaim(code, verifier));
    }

    function releaseSession(sessionId) {
        IdentityEngine.releaseSession(sessionId);
    }
}
"""


SESSION_SOURCE_QML = _HEADER_QML + """
import QtQuick
import SynQt

// The authoritative session Source on the auth entity (one instance per consuming
// edge, so each edge's emit reaches only that edge). It bridges the connect
// point to a single shared SessionManager (the `Sessions` context object): edge writes go
// into the store, and the store's changes are forwarded to every edge. A newly connected
// edge is replayed the current table (late join).
//
// Generated by `synqt build` from `identity.provider_entity`; edit the topology, not this
// file.
SessionStore {
    id: root

    function putSession(token, scope, identityJson, createdMs) {
        Sessions.applyUpsert(token, scope, identityJson, createdMs);
    }

    function removeSession(token) {
        Sessions.applyRemove(token);
    }

    function onUpserted(token, scope, identityJson, createdMs) {
        root.emitSessionUpserted(token, scope, identityJson, createdMs);
    }

    function onRemoved(token) {
        root.emitSessionRemoved(token);
    }

    Component.onCompleted: {
        Sessions.sessionUpserted.connect(onUpserted);
        Sessions.sessionRemoved.connect(onRemoved);
        const rows = Sessions.snapshot();
        for (let i = 0; i < rows.length; ++i) {
            const row = rows[i];
            root.emitSessionUpserted(row.token, row.scope, row.identityJson, row.createdMs);
        }
    }
}
"""


# The file each connect point's Source is written to, keyed by contract. The names match
# what `topologywriter` resolves for a connect point with no explicit `server:` (the owner
# entity's directory, the contract's name), so the topology and the emitted files agree
# without either naming the other.
SOURCE_QML = {"Identity": IDENTITY_SOURCE_QML, "SessionStore": SESSION_SOURCE_QML}


def render_source_qml(contract: str) -> str:
    """The Source QML bridging one framework connect point to its C++ engine."""
    try:
        return SOURCE_QML[contract]
    except KeyError:
        raise KeyError(f"no generated Source QML for the contract {contract!r}") from None
