# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Render the app's multi-binary build from the declared topology.

Two files: the project's root ``CMakeLists.txt``, which is four lines and written once,
and ``generated/synqt.cmake``, which holds every target and is rewritten on every build.

Every entity is a CMake target that links the matching SynQt runtime library
(``SynQtClient`` for the client, and one of ``SynQtService`` / ``SynQtIdentity`` /
``SynQtEdge`` for a service, per :func:`appmodel.service_libraries`) and wires in its
contracts through ``synqt_add_contract``: the client generates typed Replicas, an owner
generates the Source helper. Services are built inside ``if(NOT EMSCRIPTEN)``, so the
WebAssembly configure never sees a target that links HttpServer, NetworkAuth or Sql.

Deterministic string rendering, unit-testable without a compiler. What the topology says
is read through :mod:`synqt.appmodel`; the actual compilation runs through the CMake
presets in :mod:`synqt.build`.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Dict, List, Optional

from . import appmodel, clientbuild

_HEADER_CMAKE = ("# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux\n"
                 "# SPDX-License-Identifier: Apache-2.0\n")


def render_project_cmakelists(config: Dict[str, Any]) -> str:
    """The project's own ``CMakeLists.txt``, at the root beside ``synqt.yaml``.

    Four lines that hand the whole build to the generated tree, and the reason they are at
    the root rather than inside it is qmlcachegen. It names each compiled QML file after
    that file's path *relative to the directory of the CMakeLists that declared the module*
    (Qt6QmlMacros.cmake, `file(RELATIVE_PATH ...)`), so a module declared from
    ``generated/`` over sources in ``client/app/`` compiles into
    ``.rcc/qmlcache/app_../client/app/Main_qml.cpp``. That path is legal on Unix and
    unusable on Windows, where a name ending in dots (``app_..``) is not a directory
    anything can create: every Windows build of every project died in ninja's mkdir. Rooted
    here, the same file is ``client/app/Main.qml``, with no ``..`` to encode.

    Written once and never overwritten, because it is the one CMake file in the project a
    person may extend: add a target below the include and it survives every later build.
    """
    name = str((config.get("project") or {}).get("name") or "app")
    return "\n".join([
        _HEADER_CMAKE,
        "",
        f"# {name}, built by SynQt.",
        "#",
        "# Everything `synqt build` generates lands in generated/, which this hands the",
        "# build to. This file is yours: anything added below the include is kept.",
        "",
        "cmake_minimum_required(VERSION 3.21)",
        "",
        "# Here rather than in the generated file below it: CMake asks for a literal,",
        "# direct project() in the top-level file and warns when it finds one only inside",
        "# an include. It is also the one line here worth editing, if this build ever grows",
        "# a language beyond C++.",
        f"project({name} LANGUAGES CXX)",
        "",
        'include("${CMAKE_CURRENT_LIST_DIR}/generated/synqt.cmake")',
    ]) + "\n"


def render_root_cmakelists(config: Dict[str, Any], synqt_root: os.PathLike[str] | str,
                           project_dir: os.PathLike[str] | str | None = None) -> str:
    """The multi-binary build for the whole topology, as ``generated/synqt.cmake``.

    Included by the project's root ``CMakeLists.txt`` (:func:`render_project_cmakelists`),
    so every path a target names is rooted at the project rather than at this file, and no
    source ends up addressed through a ``..`` the toolchain has to encode into a filename.

    `project_dir` is the app the CMake is being written for. Given it, the client's QML
    module gets every QML file under the client entity's directory, not only the views
    the routes name, so a view's helper components and singletons are in the module too.
    """
    project = config.get("project", {})
    name = project.get("name", "app")
    qt_version = project.get("qt_version", "6.11.1")
    uri = appmodel.qml_uri(name)
    client = appmodel.client_entity(config)
    services = [e for e in appmodel.entities(config) if appmodel.is_service(e)]

    lines: List[str] = [_HEADER_CMAKE, "",
                        "# Generated by `synqt build` into the project's generated/ tree.",
                        "# Do not edit: it is rewritten from synqt.yaml on every build. The",
                        "# sources it names are one directory up, in the entity folders,",
                        "# where their authors wrote them.",
                        "",
                        '# project() is in the root CMakeLists.txt that includes this,',
                        '# because CMake wants that call literal and in the top-level file.',
                        'set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}")', "",
                        "# Where this file is (<project>/generated) and the project root",
                        "# above it. Taken from CMAKE_CURRENT_LIST_DIR rather than from the",
                        "# source directory, because the root CMakeLists includes this file",
                        "# rather than adding it: the source directory is the project.",
                        'set(SYNQT_GENERATED "${CMAKE_CURRENT_LIST_DIR}")',
                        'get_filename_component(SYNQT_APP_ROOT "${SYNQT_GENERATED}/.."',
                        "                       ABSOLUTE)", "",
                        "# The SynQt framework source tree (src/ runtime libraries + cmake/ helpers).",
                        "# Baked at scaffold time; override with -DSYNQT_ROOT=... to point at another checkout.",
                        f'set(SYNQT_ROOT "{Path(synqt_root).as_posix()}" '
                        'CACHE PATH "SynQt framework source root")',
                        "# The language version, the warnings that stop the build, and what release is",
                        "# allowed to strip: the same file the framework compiles itself with.",
                        'include("${SYNQT_ROOT}/cmake/SynQtBuildFlags.cmake")',
                        'include("${SYNQT_ROOT}/cmake/SynQtContracts.cmake")', "",
                        f"find_package(Qt6 {qt_version} REQUIRED COMPONENTS "
                        "Core Gui Qml Quick QuickControls2 Network RemoteObjects WebSockets)",
                        "qt_standard_project_setup(REQUIRES 6.11)", ""]

    if client is not None:
        root = Path(project_dir) if project_dir is not None else None
        client_dir = root / appmodel.entity_dir(client) if root is not None else None
        lines += _client_cmake(config, client, uri, client_dir)

    if services:
        lines += ["", "# Service entities (host only; never built for WebAssembly)",
                  "if(NOT EMSCRIPTEN)",
                  f"    find_package(Qt6 {qt_version} REQUIRED COMPONENTS Sql)"]
        lines += _runtime_library_cmake(config, services)
        # A blueprint/provider entity also links the provider library. SynQtService already
        # pulls SynQtProviders in (it PUBLIC-links it), so guard on the target to avoid
        # claiming the same binary directory twice.
        if any(appmodel.entity_type(e) in appmodel.TYPE_HELPERS or e.get("provider")
               for e in services):
            lines += ['    if(NOT TARGET SynQtProviders)',
                      '        add_subdirectory("${SYNQT_ROOT}/src/providers" '
                      '"${CMAKE_BINARY_DIR}/SynQtProviders")',
                      '    endif()']
        for entity in services:
            lines += _service_cmake(config, entity)
        lines.append("endif()")

    lines += _tests_cmake(config, qt_version,
                          Path(project_dir) if project_dir is not None else None)

    return "\n".join(lines) + "\n"


def _runtime_library_cmake(config: Dict[str, Any],
                           services: List[Dict[str, Any]]) -> List[str]:
    """Add only the SynQt runtime libraries this topology actually needs.

    Not an optimization. Qt HTTP Server and Qt Network Authorization are GPLv3-only, so a
    project with no web edge and no auth entity must neither link them nor require them to
    be installed; adding src/edge unconditionally would do both, and its
    THIRD-PARTY-LICENSES would be wrong about it. Each directory guards its own
    dependencies with `if(NOT TARGET ...)`, so listing several here is safe and the order
    only decides which scope creates a target.
    """
    needed = {library for entity in services
              for library in appmodel.service_libraries(config, entity)}
    lines: List[str] = []
    for library in ("SynQtService", "SynQtIdentity", "SynQtEdge", "SynQtGateway"):
        if library not in needed:
            continue
        folder = appmodel.SERVICE_LIBRARIES[library]
        lines += [f"    if(NOT TARGET {library})",
                  f'        add_subdirectory("${{SYNQT_ROOT}}/{folder}" '
                  f'"${{CMAKE_BINARY_DIR}}/{library}")',
                  "    endif()"]
    return lines


def _tests_cmake(config: Dict[str, Any], qt_version: str,
                 project_dir: Optional[Path]) -> List[str]:
    """Wire in the application's own test target, when it has tests to build.

    `enable_testing()` is unconditional: without it there is no CTestTestfile.cmake and
    `synqt test` cannot tell a project with no tests from a project that was never
    configured for them. With it, no tests is an honest zero.

    The target itself is defined in its own directory rather than here, and that is not
    tidiness. repc emits `moc_rep_<contract>_source.cpp` into the *directory's* binary dir,
    not the target's, so a second target in this directory generating the same contract at
    the same role collides with the first: "Files to be generated by multiple different
    commands". The test target owns every contract at ROLE source, and so does each service
    entity, so the two cannot share a directory.
    """
    lines = ["", "enable_testing()"]
    if not appmodel.test_qml_files(project_dir):
        return lines

    return lines + [
        "",
        "# The application's own tests: QML, driven through the SynQt.Test harness. Host",
        "# only, because a test runs where the entity runs, never in a browser.",
        "if(NOT EMSCRIPTEN)",
        f"    find_package(Qt6 {qt_version} REQUIRED COMPONENTS QuickTest)",
        # Its own directory under generated/, for the repc reason spelled out above.
        '    add_subdirectory("${SYNQT_GENERATED}/tests"'
        ' "${CMAKE_BINARY_DIR}/app-tests")',
        "endif()",
    ]


def render_tests_cmakelists(config: Dict[str, Any]) -> str:
    """The generated `generated/tests/CMakeLists.txt` defining the app test target.

    It reads `SYNQT_APP_ROOT` from the parent scope for the paths that are in the source
    tree (the contracts and the tests themselves), because its own directory holds nothing
    but generated files.
    """
    contracts = appmodel.contract_paths(config)
    lines = [_HEADER_CMAKE, "",
             "# Generated by `synqt build`. Do not edit; it is rewritten from synqt.yaml.",
             "#",
             "# A directory of its own so repc's per-directory output does not collide with",
             "# the service entities generating the same contracts at the same role.",
             "",
             "if(NOT TARGET SynQtTesting)",
             '    add_subdirectory("${SYNQT_ROOT}/src/testing" "${CMAKE_BINARY_DIR}/SynQtTesting")',
             "endif()",
             "",
             "qt_add_executable(app_tests tests_main.cpp)"]
    # Every contract's Source half, because a test drives an owner and any connect point in
    # the project may be the one under test.
    forwarding = appmodel.session_forwarding_contracts(config)
    for contract, relative in contracts.items():
        carries = " FORWARDS_SESSION" if contract in forwarding else ""
        lines.append(f"synqt_add_contract(app_tests ROLE source{carries} "
                     f'SYN "${{SYNQT_APP_ROOT}}/{relative}")')
    lines += [
        "",
        "# Qt Quick Test discovers the tst_*.qml files by directory at run time, so adding",
        "# a test file needs no rebuild of anything but the list ctest reports.",
        "target_compile_definitions(app_tests PRIVATE",
        '    QUICK_TEST_SOURCE_DIR="${SYNQT_APP_ROOT}/tests")',
        "target_link_libraries(app_tests PRIVATE",
        "    SynQtTesting Qt6::Core Qt6::Gui Qt6::Qml Qt6::Quick Qt6::QuickTest",
        "    Qt6::RemoteObjects)",
        "",
        "# offscreen: a slot draws nothing, and a test target that needed a display would",
        "# not run in CI.",
        "add_test(NAME app-tests COMMAND app_tests -platform offscreen)",
    ]
    return "\n".join(lines) + "\n"


def _client_cmake(config: Dict[str, Any], client: Dict[str, Any], uri: str,
                  client_dir: Optional[Path] = None) -> List[str]:
    name = client.get("name", "client")
    consumed = appmodel.consumed_by(config, name)
    contracts = appmodel.contracts_of(consumed)
    # The window, every view a route names, and every other QML file the client entity
    # holds: a file outside the module is not in the resource system, so neither the URL
    # the route table carries nor a view's own `Card {}` would resolve to anything.
    views = appmodel.client_qml_files(config, client_dir)
    folder = appmodel.entity_dir(client)
    # From the mirror under generated/, not from the entity folder: that is the copy whose
    # root objects are loadable (synqt.qmlrewrite). It changes nothing about where a view
    # ends up in the resource system, because every file below is given an explicit
    # QT_RESOURCE_ALIAS of its bare name, which is what the route table and
    # loadFromModule() address it by.
    qml_files = ['"${SYNQT_GENERATED}/%s/%s"' % (folder, view) for view in views]
    lines = ["# The client (browser WASM and native desktop, from one QML)",
             'add_subdirectory("${SYNQT_ROOT}/src/client" "${CMAKE_BINARY_DIR}/SynQtClient")']
    # Each file is listed by absolute path, and each has to land where it sits in the
    # entity directory: the module root is where loadFromModule() looks for Main and
    # where the compiled route table points (qrc:/qt/qml/<Uri>/<view>). Without an alias
    # the entity directory would become part of the resource path and neither would
    # resolve. A `pragma Singleton` file is also marked as one, or the module would
    # register it as an ordinary type and a view reading `Theme.color` would not compile.
    for view, qml_file in zip(views, qml_files):
        singleton = (client_dir is not None
                     and appmodel.declares_singleton(client_dir / view))
        properties = ("QT_QML_SINGLETON_TYPE TRUE " if singleton else "")
        lines.append("set_source_files_properties(%s\n"
                     "    PROPERTIES %sQT_RESOURCE_ALIAS %s)"
                     % (qml_file, properties, view))
    lines += [
             'set(SYNQT_EDGE_URL "wss://127.0.0.1:8443/sync" CACHE STRING '
             '"Desktop client edge URL")',
             f'qt_add_executable({name} '
             f'"${{SYNQT_GENERATED}}/{folder}/main.cpp")',
             f"qt_add_qml_module({name}",
             f"    URI {uri}",
             "    VERSION 1.0",
             "    QML_FILES"]
    lines += ["        " + qml_file for qml_file in qml_files]
    lines.append(")")
    paths = appmodel.contract_paths(config)
    forwarding = appmodel.session_forwarding_contracts(config)
    for contract in contracts:
        carries = " FORWARDS_SESSION" if contract in forwarding else ""
        lines.append(f"synqt_add_contract({name} ROLE replica{carries} "
                     f'SYN "${{SYNQT_APP_ROOT}}/{paths[contract]}")')
    lines += [f'target_compile_definitions({name} PRIVATE SYNQT_EDGE_URL="${{SYNQT_EDGE_URL}}")',
              f"target_link_libraries({name} PRIVATE",
              "    SynQtClient Qt6::Core Qt6::Gui Qt6::Qml Qt6::Quick Qt6::QuickControls2",
              "    Qt6::Network Qt6::RemoteObjects Qt6::WebSockets)",
              "if(EMSCRIPTEN)",
              "    # Read window.location through Embind (no eval) and drop the eval-based",
              "    # Emscripten runtime, so the edge's strict CSP (no 'unsafe-eval') holds.",
              f'    target_link_options({name} PRIVATE "-lembind" "-sDYNAMIC_EXECUTION=0")']
    if clientbuild.client_asyncify(config):
        lines += [
            "    # build.client_asyncify: link with asyncify, so the main thread suspends",
            "    # inside processEvents() and any browser event drives a posted-event sweep,",
            "    # instead of the single zero-delay wakeup callback being the only one that",
            "    # can. -Os is Emscripten's own recommendation for asyncify, and the stack is",
            "    # raised from the 4 KB default because the suspend point sits under the whole",
            "    # Qt event-dispatch stack.",
            f'    target_link_options({name} PRIVATE',
            '        "-sASYNCIFY" "-sASYNCIFY_STACK_SIZE=131072" "-Os")']
    lines += ["endif()"]
    lines += _macos_bundle_cmake(config, name)
    lines += _linux_rpath_cmake(name)
    return lines


def _linux_rpath_cmake(name: str) -> List[str]:
    """Let the Linux desktop client find the Qt that `--deploy` puts beside it.

    Without this the only rpath is the absolute path of the kit it was built against, so the
    deployed binary run directly (rather than through the generated launcher, which sets
    LD_LIBRARY_PATH and therefore wins over any rpath) silently loads the build machine's Qt
    and looks fine there, while on any other machine it finds nothing at all.

    BUILD_RPATH rather than INSTALL_RPATH, because nothing here runs `cmake --install`: the
    build copies the binary out of the build tree (build.py `_install_binary`), so the install
    rpath would never be applied and this would be a setting that reads correct and does
    nothing. CMake appends this after the kit path it derives from the link line, which is the
    right order either way: on the build machine the kit answers first and is the same Qt, and
    everywhere else it does not exist and `$ORIGIN/lib` does.
    """
    return ["if(UNIX AND NOT APPLE AND NOT EMSCRIPTEN)",
            f"    set_target_properties({name} PROPERTIES",
            '        BUILD_RPATH "$ORIGIN/lib")',
            "endif()"]


def _macos_bundle_cmake(config: Dict[str, Any], name: str) -> List[str]:
    """Make the macOS desktop client an .app bundle rather than a bare executable.

    Not cosmetic, and not the deployment step docs/desktop.md deliberately leaves to the
    developer. `macdeployqt` takes an .app and nothing else, so a bare Mach-O makes that
    documented hand-off impossible to perform at all: the developer would have to rewrite the
    generated CMake before they could run the command DEPLOY.txt tells them to run. A bare
    executable is also not an app in the sense macOS means it (no Info.plist, so no name in the
    menu bar, no icon slot, and nothing to sign or notarize later).

    The identifier is a cache variable rather than a config key on purpose. docs/desktop.md
    places bundle identifiers with signing in the deployment step, so this stays out of
    synqt.yaml; a CMake cache entry is the escape hatch for someone who needs to set it before
    they sign, and it defaults to a placeholder that is obviously meant to be replaced.
    """
    project = config.get("project", {}) if isinstance(config.get("project"), dict) else {}
    app = project.get("name") or name
    version = str(project.get("version") or "0.1.0")
    return ["if(APPLE AND NOT IOS)",
            f'    set(SYNQT_BUNDLE_ID "com.example.{app}.{name}" CACHE STRING',
            '        "macOS bundle identifier for the desktop client")',
            f"    set_target_properties({name} PROPERTIES",
            "        MACOSX_BUNDLE TRUE",
            f'        MACOSX_BUNDLE_BUNDLE_NAME "{name}"',
            '        MACOSX_BUNDLE_GUI_IDENTIFIER "${SYNQT_BUNDLE_ID}"',
            f'        MACOSX_BUNDLE_BUNDLE_VERSION "{version}"',
            f'        MACOSX_BUNDLE_SHORT_VERSION_STRING "{version}")',
            "endif()"]


def _service_cmake(config: Dict[str, Any], entity: Dict[str, Any]) -> List[str]:
    name = entity.get("name")
    # Framework connect points are filtered out on both sides: their contracts live in
    # the runtime libraries and are compiled into them, so an app has no
    # `Identity.syn` of its own to point a synqt_add_contract at. That is what makes
    # promoting identity to its own entity a one-line change to synqt.yaml and nothing else.
    owned = appmodel.app_points(appmodel.owned_by(config, name))
    consumed = appmodel.app_points(appmodel.mesh_consumed(config, name))
    # SynQtService, SynQtIdentity or SynQtEdge, by what this entity is. The same call
    # decides what its THIRD-PARTY-LICENSES says it links (licenses.py).
    libs = list(appmodel.service_libraries(config, entity))
    if appmodel.entity_type(entity) in appmodel.TYPE_HELPERS or entity.get("provider"):
        libs.append("SynQtProviders")
    folder = appmodel.entity_dir(entity)
    paths = appmodel.contract_paths(config)
    lines = ["", f"    qt_add_executable({name} "
             f'"${{SYNQT_GENERATED}}/{folder}/main.cpp")']
    # Whether a contract's slots carry a forwarded session is the topology's answer, not the
    # contract's, and both sides of a link read it from here so they cannot disagree.
    forwarding = appmodel.session_forwarding_contracts(config)
    for role, points in (("source", owned), ("replica", consumed)):
        for contract in appmodel.contracts_of(points):
            carries = " FORWARDS_SESSION" if contract in forwarding else ""
            lines.append(f"    synqt_add_contract({name} ROLE {role}{carries} "
                         f'SYN "${{SYNQT_APP_ROOT}}/{paths[contract]}")')
    # Qt6::Gui for the edge because its main runs a QGuiApplication. A service runs a
    # QCoreApplication and gets Gui only if it owns a connect point, where it arrives with
    # SynQtContract (the published model is a QStandardItemModel).
    qt_modules = "Qt6::Core Qt6::Gui Qt6::Network Qt6::Qml" if appmodel.is_edge(entity) \
        else "Qt6::Core Qt6::Network Qt6::Qml"
    link = " ".join(libs)
    lines += [f"    target_link_libraries({name} PRIVATE",
              f"        {link} {qt_modules}",
              "        Qt6::RemoteObjects Qt6::WebSockets)"]
    lines += _custom_provider_cmake(entity, name)
    return lines


def _custom_provider_cmake(entity: Dict[str, Any], name: str) -> List[str]:
    """Compile `providers/custom/` into an entity that selects a `custom:` provider.

    A custom provider is only reachable once its registration macro has run, and that macro
    runs because the file is linked into the entity. Nothing else picks these files up:
    this file rewrites the root CMakeLists on every build, so a hand-added `target_sources`
    would not survive one. Globbing keeps `synqt add provider` honest, since what it writes
    is compiled with no further step, and CONFIGURE_DEPENDS means a provider added later is
    picked up by the next build rather than needing CMake re-run by hand.

    Every file in the directory goes into every entity that selects a custom provider. A
    registration only publishes a name under `custom:`, and a family factory looks up the
    one name that entity's config selected, so an entity carrying a registration it does not
    use has a symbol it never reaches, not a provider it did not ask for.
    """
    provider = entity.get("provider") or {}
    if not str(provider.get("name", "")).startswith("custom:"):
        return []
    variable = "SYNQT_CUSTOM_PROVIDERS_%s" % name.upper().replace("-", "_")
    return ["",
            "    # This entity selects a custom: provider, so its implementation is linked in.",
            f"    file(GLOB {variable} CONFIGURE_DEPENDS",
            '        "${SYNQT_APP_ROOT}/providers/custom/*.cpp")',
            f"    if({variable})",
            f"        target_sources({name} PRIVATE ${{{variable}}})",
            "    endif()"]
