# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Turn a connect point's ``export:`` block into the ``.syn`` the compiler reads.

A connect point and the shape of what crosses it are one thing, so they are written in one
place: the point's ``export:`` in ``synqt.yaml`` holds the members, and nothing names the
contract, because the point is already named.

    connect_points:
      - name: auction
        owner: edge
        consumers: [app]
        export: |
          prop string itemName
          prop int highBid
          slot placeBid(int amount)
          signal bidRejected(string reason)

What the generator wants is a file, so one is written under ``generated/`` beside the
entity's generated main: ``generated/web/edge/Auction.syn``. Its name is the point's,
capitalized, which is also the QML type the point's server file is rooted at. Nobody edits
it; editing the ``export:`` block rewrites it.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any, Dict, List

from synqt import appmodel, writer

_HEADER = ("// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux\n"
           "// SPDX-License-Identifier: Apache-2.0\n")

#: A `record` is a type, not a member, so it is written outside the contract even though it
#: is declared inside the same block. Lifting it here is what lets one `export:` hold both.
_RECORD = re.compile(r"^\s*record\b")


def export_text(point: Dict[str, Any]) -> str:
    """The ``export:`` block of a connect point, empty when it declares none."""
    declared = point.get("export")
    return declared if isinstance(declared, str) else ""


def has_export(point: Dict[str, Any]) -> bool:
    """Did this point declare an ``export:`` block at all (even an empty one)?"""
    return isinstance(point.get("export"), str)


def contract_source(name: str, point: Dict[str, Any]) -> str:
    """The ``.syn`` text for one connect point's contract.

    Members go inside ``contract <Name> { ... }``; a ``record`` line goes above it, because
    a record is a type the members use rather than a member itself. Comments and blank
    lines are kept as written: the block is the author's, and this only puts a frame
    around it.
    """
    records: List[str] = []
    members: List[str] = []
    for line in export_text(point).splitlines():
        if _RECORD.match(line):
            records.append(line.strip())
        elif line.strip():
            members.append("    " + line.strip())
        else:
            members.append("")
    while members and not members[-1]:
        members.pop()
    lines = [_HEADER.rstrip("\n"),
             f"// Generated by synqt from the '{point.get('name')}' connect point in "
             "synqt.yaml. Do not edit.",
             ""]
    if records:
        lines += records + [""]
    lines += [f"contract {name} {{"] + members + ["}"]
    return "\n".join(lines) + "\n"


def write_contracts(project_dir: os.PathLike[str] | str,
                    config: Dict[str, Any]) -> List[str]:
    """Write every app connect point's contract under ``generated/``.

    Returns the project-relative paths this owns, written or already current. A framework
    connect point is skipped: its contract ships in the runtime library that owns it, and
    the project has no ``export:`` to write it from.
    """
    root = Path(project_dir)
    owners = {str(entity.get("name") or ""): entity
              for entity in appmodel.entities(config)}
    written: List[str] = []
    for point in appmodel.app_points(appmodel.connect_points(config)):
        owner = owners.get(str(point.get("owner") or ""))
        contract = appmodel.contract_of(point)
        if owner is None or not contract:
            continue
        relative = appmodel.contract_path(owner, contract)
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        writer.write_if_changed(target, contract_source(contract, point))
        written.append(relative)
    return written
