# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Render the monitor entity's two Source QML bridges.

A monitor owns two framework connect points: ``ingest``, which every service reports
through, and ``console``, which the operator's client reads. Both need an owner-side Source,
and both are the same in every project: they forward each slot to the C++ engine the
generated ``main.cpp`` puts in their context, and publish its answers back out.

That is why they are generated rather than asked for. Adding a monitor is one line of
configuration, so the files that line implies are emitted here, next to the generated
``main.cpp`` that supplies their context object. It is the same arrangement as
:mod:`synqt.authentity`, for the same reason.
"""

from __future__ import annotations

_HEADER_QML = ("// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux\n"
               "// SPDX-License-Identifier: Apache-2.0\n")


INGEST_SOURCE_QML = _HEADER_QML + """
import SynQt

// The monitor's ingest Source: one instance per reporting entity, so `Caller.entity` is
// that entity and nothing else. It forwards each batch to the `Monitor` engine along with
// the name the transport verified, which is what stops an entity reporting as another one:
// the name the batch carried is never read.
//
// Generated by `synqt build` from `monitoring.entity`; edit the topology, not this file.
Ingest {
    id: root

    function publish(events) {
        Monitor.take(events, Caller.entity);
    }

    function heartbeat(entity, sentMs) {
        // The name it says, ignored in favour of the one its certificate proves, for the
        // same reason as above. An entity may be wrong about its own name; it cannot be
        // wrong about its certificate.
        Monitor.heartbeat(Caller.entity, sentMs);
    }
}
"""


CONSOLE_SOURCE_QML = _HEADER_QML + """
import SynQt

// The monitor's console Source: one instance per operator, because the filter is theirs.
// Two operators looking at different things is the normal case, not a special one.
//
// Everything it publishes comes from the `Monitor` engine, which is what keeps this file
// generic: no type here knows what the system being watched is made of.
//
// Generated by `synqt build` from `monitoring.entity`; edit the topology, not this file.
Console {
    id: root

    // What this operator last asked for, so a batch arriving republishes their view and
    // not everybody's.
    property string askedText: ""
    property string askedEntity: ""
    property string askedSeverity: "trace"
    property int askedLimit: 500
    property string followedTrace: ""

    function ask(text, entity, minimumSeverity, limit) {
        root.followedTrace = "";
        root.askedText = text;
        root.askedEntity = entity;
        root.askedSeverity = minimumSeverity;
        root.askedLimit = limit;
        root.refresh();
    }

    function follow(traceId) {
        if (traceId.length === 0) {
            root.emitRefused("That event is not part of a trace.");
            return;
        }
        root.followedTrace = traceId;
        root.refresh();
    }

    function refresh() {
        if (root.followedTrace.length > 0) {
            root.eventsRows = Monitor.follow(root.followedTrace);
        } else {
            root.eventsRows = Monitor.ask(root.askedText, root.askedEntity,
                                          root.askedSeverity, root.askedLimit);
        }
        root.entitiesRows = Monitor.entityRows();
    }

    received: Monitor.received
    stored: Monitor.stored
    dropped: Monitor.dropped

    Component.onCompleted: {
        Monitor.arrived.connect(root.refresh);
        root.refresh();
    }
}
"""


#: The file each connect point's Source is written to, keyed by contract. The names match
#: what `topologywriter` resolves for a connect point with no explicit `server:`, so the
#: topology and the emitted files agree without either naming the other.
SOURCE_QML = {"Ingest": INGEST_SOURCE_QML, "Console": CONSOLE_SOURCE_QML}


def render_source_qml(contract: str) -> str:
    """The Source QML bridging one monitor connect point to its C++ engine."""
    try:
        return SOURCE_QML[contract]
    except KeyError:
        raise KeyError(f"no generated Source QML for the contract {contract!r}") from None
