# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Lower a parsed :class:`SynFile` to the generated C++/rep artifacts.

Three outputs per contract file:

* the ``.rep`` (records -> POD, prop -> PROP READPUSH, model -> MODEL with only its
  declared roles, signal -> SIGNAL, slot -> SLOT with the return type when present);
* the owner-side Source helper (``<Contract>Source`` in QML), whose
  ``set<Model>(rows)`` keeps only declared roles and drops undeclared row fields;
* the consumer-side Replica QML registration.
"""

from __future__ import annotations

from typing import List

from .model import Contract, Model, Signal, Slot, SynFile
from .types import cpp_type

SPDX_CPP = (
    "// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux\n"
    "// SPDX-License-Identifier: Apache-2.0\n"
    "// Generated by synqtc from a .syn contract. Do not edit.\n"
)


def _cap(name: str) -> str:
    return name[:1].upper() + name[1:]


def _param_list(params, record_names, path) -> str:
    return ", ".join(
        f"{cpp_type(param.type, record_names, path=path, line=param.line, col=param.col)} {param.name}"
        for param in params
    )


# --------------------------------------------------------------------------- rep


def emit_rep(syn: SynFile) -> str:
    records = syn.record_names
    path = f"{syn.stem}.syn"
    lines: List[str] = [SPDX_CPP.rstrip("\n"), ""]

    for record in syn.records:
        fields = ", ".join(
            f"{cpp_type(f.type, records, path=path, line=f.line, col=f.col)} {f.name}"
            for f in record.fields
        )
        lines.append(f"POD {record.name}({fields})")
    if syn.records:
        lines.append("")

    for contract in syn.contracts:
        lines.append(f"class {contract.name}")
        lines.append("{")
        for member in contract.members:
            lines.append("    " + _lower_member(member, records, path))
        lines.append("}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def _lower_member(member, records, path) -> str:
    if isinstance(member, Model):
        return f"MODEL {member.name}({', '.join(member.roles)})"
    if isinstance(member, Signal):
        return f"SIGNAL({member.name}({_param_list(member.params, records, path)}))"
    if isinstance(member, Slot):
        params = _param_list(member.params, records, path)
        if member.return_type is None:
            return f"SLOT(void {member.name}({params}))"
        ret = cpp_type(member.return_type, records, path=path, line=member.line, col=member.col)
        return f"SLOT({ret} {member.name}({params}))"
    # Prop: READPUSH is the SynQt default and is written explicitly for clarity.
    ctype = cpp_type(member.type, records, path=path, line=member.line, col=member.col)
    return f"PROP({ctype} {member.name} READPUSH)"


# ------------------------------------------------------------------- source side


def _has_models(syn: SynFile) -> bool:
    return any(contract.models for contract in syn.contracts)


def emit_source_helper_header(syn: SynFile, lstem: str) -> str:
    # <lstem>_rep.h is an indirection the build writes to the correct repc header for
    # this target's role (_source, _replica, or _merged), so the helper compiles the
    # same way whether the target is an owner or a both-sided test.
    out: List[str] = [SPDX_CPP, "#pragma once", "",
                      f'#include "{lstem}_rep.h"', "",
                      "#include <QList>",
                      "#include <QObject>",
                      "#include <QQmlListProperty>", ""]
    # QStandardItemModel is QtGui; only pull it in when a contract actually has a
    # model, so a model-less service does not need QtGui.
    if _has_models(syn):
        out += ["#include <QStandardItemModel>", "#include <QVariantList>", ""]
    records = syn.record_names
    path = f"{syn.stem}.syn"
    for contract in syn.contracts:
        out.append(_source_helper_class(contract, records, path))
        out.append("")
    # The typed Caller subclass (emit<Signal> sugar) is only meaningful when this Source is
    # hosted by the service runtime, which is the only thing that binds a Caller. Guard it on
    # the runtime's caller.h so a standalone contract target (rep-only) still compiles.
    caller_subclasses = [_caller_subclass(contract, records, path)
                         for contract in syn.contracts if contract.signals]
    if caller_subclasses:
        out += ["#if __has_include(<caller.h>)",
                "#  include <caller.h>", "", "#  include <QVariant>", ""]
        out += caller_subclasses
        out += ["#endif", ""]
    out.append(f"void synqtRegister{_cap(syn.stem)}Sources();")
    out.append("")
    return "\n".join(out)


def _caller_subclass(contract: Contract, records, path) -> str:
    # A per-contract Caller whose emit<Signal>(...) methods forward to the inherited
    # emitSignal, giving owner QML the Caller.emit<Signal>(...) sugar (e.g.
    # Caller.emitRejected(reason)). The per-connection Source has a single consumer, so the
    # signal reaches this caller alone.
    name = contract.name
    lines = [
        f"// Typed Caller for {name}: Caller.emit<Signal>(...) sugar over emitSignal.",
        f"class {name}Caller : public SynQt::Caller",
        "{",
        "    Q_OBJECT",
        "",
        "public:",
        f"    explicit {name}Caller(QObject *parent = nullptr) : SynQt::Caller{{parent}} {{}}",
        "",
    ]
    for signal in contract.signals:
        params = _param_list(signal.params, records, path)
        variants = "".join(", QVariant::fromValue(%s)" % p.name for p in signal.params)
        lines.append(
            f"    Q_INVOKABLE void emit{_cap(signal.name)}({params})")
        lines.append(
            f'    {{ emitSignal(QStringLiteral("{signal.name}"){variants}); }}')
    lines.append("};")
    return "\n".join(lines)


def _source_helper_class(contract: Contract, records, path) -> str:
    name = contract.name
    lines = [
        "// Owner-side helper: the QML type the connect point's server file derives",
        f"// from (registered as \"{name}Source\"). Props and signals are inherited from",
        "// the generated Source; set<Model>(rows) publishes a model limited to its",
        "// declared roles, dropping any undeclared owner-only fields at the boundary.",
        f"class {name}SourceHelper : public {name}SimpleSource",
        "{",
        "    Q_OBJECT",
        "    // A generated Source is not a visual item, so its default property is a plain",
        "    // QObject child list: this lets the owner's server file declare non-visual QML",
        "    // children (Timer, Connections, ...) inside the Source to drive itself.",
        '    Q_CLASSINFO("DefaultProperty", "data")',
        "    Q_PROPERTY(QQmlListProperty<QObject> data READ data DESIGNABLE false)",
        "",
        "public:",
        f"    explicit {name}SourceHelper(QObject *parent = nullptr);",
        "",
        "    QQmlListProperty<QObject> data();",
        "",
    ]
    for model in contract.models:
        lines.append(f"    Q_INVOKABLE void set{_cap(model.name)}(const QVariantList &rows);")
    if contract.models:
        lines.append("")
    if contract.slots:
        lines.append("    // Consumer -> owner requests. Each dispatches to the owner's QML")
        lines.append("    // implementation (a QML function of the same name); a slot the owner")
        lines.append("    // did not implement is a no-op (or returns a default).")
        for slot in contract.slots:
            lines.append("    " + _slot_signature(slot, records, path) + " override;")
        lines.append("")
    if contract.signals:
        lines.append("    // Deliver a contract signal to the acquiring consumer(s). On a")
        lines.append("    // per_session/per_peer instance the sole consumer is the caller, so")
        lines.append("    // Caller.emitSignal(\"<Signal>\", ...) routes here to answer one caller.")
        for signal in contract.signals:
            params = _param_list(signal.params, records, path)
            lines.append(f"    Q_INVOKABLE void emit{_cap(signal.name)}({params});")
        lines.append("")
    lines.append("private:")
    lines.append("    static void appendData(QQmlListProperty<QObject> *list, QObject *object);")
    lines.append("    QList<QObject *> m_data;")
    for model in contract.models:
        lines.append(f"    QStandardItemModel m_{model.name}Model;")
    lines.append("};")
    return "\n".join(lines)


def _slot_signature(slot: Slot, records, path) -> str:
    params = _param_list(slot.params, records, path)
    if slot.return_type is None:
        return f"void {slot.name}({params})"
    ret = cpp_type(slot.return_type, records, path=path, line=slot.line, col=slot.col)
    return f"{ret} {slot.name}({params})"


SLOT_DISPATCH_HELPER = """namespace {
// Dispatch a consumer's slot call to the owner's QML implementation. A QML `function`
// with the slot's name is added to the object's meta-object beyond the generated
// helper's own C++ methods (cppMethodCount); if one exists, this returns its index so
// the slot can invoke it. Returns -1 when the owner did not implement the slot in QML,
// in which case the slot is a no-op (or returns a default), never recursing into itself.
int synqtQmlSlotIndex(const QObject *object, const char *name, int paramCount,
                      int cppMethodCount)
{
    const QMetaObject *metaObject{object->metaObject()};
    for (int index{metaObject->methodCount() - 1}; index >= cppMethodCount; --index) {
        const QMetaMethod method{metaObject->method(index)};
        if (method.name() == name && method.parameterCount() == paramCount) {
            return index;
        }
    }
    return -1;
}
} // namespace
"""


def emit_source_helper_source(syn: SynFile, lstem: str) -> str:
    out: List[str] = [SPDX_CPP,
                      f'#include "{lstem}_sourcehelper.h"', "",
                      "#include <QMetaMethod>",
                      "#include <QQmlEngine>",
                      "#include <QQmlListProperty>",
                      "#include <QVariant>", ""]
    if _has_models(syn):
        out += ["#include <QStandardItem>", ""]
    has_slots = any(contract.slots for contract in syn.contracts)
    if has_slots:
        out += [SLOT_DISPATCH_HELPER, ""]
    records = syn.record_names
    path = f"{syn.stem}.syn"
    for contract in syn.contracts:
        out.append(_source_helper_impl(contract, records, path))
        out.append("")

    out.append(f"void synqtRegister{_cap(syn.stem)}Sources()")
    out.append("{")
    for contract in syn.contracts:
        out.append(
            f'    qmlRegisterType<{contract.name}SourceHelper>("SynQt", 1, 0, "{contract.name}Source");'
        )
    # Install the typed Caller factory when the service runtime is present (same guard as the
    # subclass in the header), so forUser/forEntity mint the <Contract>Caller for this
    # contract and QML gets Caller.emit<Signal>(...).
    caller_contracts = [contract for contract in syn.contracts if contract.signals]
    if caller_contracts:
        out.append("#if __has_include(<caller.h>)")
        for contract in caller_contracts:
            out.append(
                f'    SynQt::Caller::registerCallerFactory(QStringLiteral("{contract.name}"),'
            )
            out.append(
                f"        [](QObject *parent) -> SynQt::Caller * "
                f"{{ return new {contract.name}Caller{{parent}}; }});"
            )
        out.append("#endif")
    out.append("}")
    out.append("")
    return "\n".join(out)


def _source_helper_impl(contract: Contract, records, path) -> str:
    name = contract.name
    lines: List[str] = []

    lines.append(f"{name}SourceHelper::{name}SourceHelper(QObject *parent)")
    lines.append(f"    : {name}SimpleSource{{parent}}")
    lines.append("{")
    for model in contract.models:
        lines.append(f"    set{_cap(model.name)}({{}});")
    lines.append("}")
    lines.append("")

    # The default child list: accept non-visual QML children declared in the Source. The
    # QML engine still calls componentComplete on each (so a child Timer with running:true
    # starts), independent of this object not being a visual parent.
    lines.append(f"QQmlListProperty<QObject> {name}SourceHelper::data()")
    lines.append("{")
    lines.append("    return QQmlListProperty<QObject>{this, nullptr,")
    lines.append(f"                                     &{name}SourceHelper::appendData,")
    lines.append("                                     nullptr, nullptr, nullptr};")
    lines.append("}")
    lines.append("")
    lines.append(f"void {name}SourceHelper::appendData(QQmlListProperty<QObject> *list,")
    lines.append("                                    QObject *object)")
    lines.append("{")
    lines.append("    if (!object) {")
    lines.append("        return;")
    lines.append("    }")
    lines.append(f"    {name}SourceHelper *self{{qobject_cast<{name}SourceHelper *>(list->object)}};")
    lines.append("    if (!self) {")
    lines.append("        return;")
    lines.append("    }")
    lines.append("    object->setParent(self);")
    lines.append("    self->m_data.append(object);")
    lines.append("}")
    lines.append("")

    for model in contract.models:
        lines.append(_set_model_impl(name, model))
        lines.append("")

    for slot in contract.slots:
        lines.append(_slot_impl(name, slot, records, path))
    if contract.slots:
        lines.append("")

    for signal in contract.signals:
        lines.append(_emit_signal_impl(name, signal, records, path))
        lines.append("")

    return "\n".join(lines).rstrip("\n")


def _emit_signal_impl(class_name: str, signal: Signal, records, path) -> str:
    params = _param_list(signal.params, records, path)
    args = ", ".join(p.name for p in signal.params)
    return "\n".join([
        f"void {class_name}SourceHelper::emit{_cap(signal.name)}({params})",
        "{",
        f"    Q_EMIT {signal.name}({args});",
        "}",
    ])


def _set_model_impl(class_name: str, model: Model) -> str:
    roles = model.roles
    role_array = ", ".join(f'QByteArrayLiteral("{role}")' for role in roles)
    lines = [
        f"void {class_name}SourceHelper::set{_cap(model.name)}(const QVariantList &rows)",
        "{",
        f"    static const QList<QByteArray> declaredRoles{{{role_array}}};",
        f"    m_{model.name}Model.clear();",
        "    QHash<int, QByteArray> roleNames;",
        "    for (int roleIndex{0}; roleIndex < declaredRoles.size(); ++roleIndex) {",
        "        roleNames.insert(Qt::UserRole + roleIndex, declaredRoles.at(roleIndex));",
        "    }",
        f"    m_{model.name}Model.setItemRoleNames(roleNames);",
        "    for (const QVariant &rowVariant : rows) {",
        "        const QVariantMap row{rowVariant.toMap()};",
        "        QStandardItem *item{new QStandardItem{}};",
        "        for (int roleIndex{0}; roleIndex < declaredRoles.size(); ++roleIndex) {",
        "            // Only declared roles cross; undeclared row fields are dropped here.",
        "            item->setData(row.value(QString::fromUtf8(declaredRoles.at(roleIndex))),",
        "                          Qt::UserRole + roleIndex);",
        "        }",
        f"        m_{model.name}Model.appendRow(item);",
        "    }",
        f"    {class_name}SimpleSource::set{_cap(model.name)}(&m_{model.name}Model);",
        "}",
    ]
    return "\n".join(lines)


def _slot_impl(class_name: str, slot: Slot, records, path) -> str:
    helper = f"{class_name}SourceHelper"
    is_void = slot.return_type is None
    ret = "void" if is_void else cpp_type(
        slot.return_type, records, path=path, line=slot.line, col=slot.col)
    params = _param_list(slot.params, records, path)
    head = f"{ret} {helper}::{slot.name}({params})"

    # The owner implements the slot as a QML `function`, whose parameters are untyped
    # (QVariant) and whose return is a QVariant. Marshal every argument as a QVariant so
    # the invoke matches the QML method's signature, and convert a return back to its
    # declared C++ type. (Passing Q_ARG(<cppType>, ...) would silently fail to match.)
    arg_terms = [
        f"Q_ARG(QVariant, QVariant::fromValue({p.name}))" for p in slot.params
    ]
    arg_suffix = ("".join(", " + term for term in arg_terms))

    lines = [
        f'    const int index{{synqtQmlSlotIndex(this, "{slot.name}", {len(slot.params)},',
        f"                                     {helper}::staticMetaObject.methodCount())}};",
    ]
    if is_void:
        lines += [
            "    if (index >= 0) {",
            f"        metaObject()->method(index).invoke(this, Qt::DirectConnection{arg_suffix});",
            "    }",
        ]
    else:
        lines += [
            "    QVariant result{};",
            "    if (index >= 0) {",
            "        metaObject()->method(index).invoke(this, Qt::DirectConnection,",
            f"                                           Q_RETURN_ARG(QVariant, result){arg_suffix});",
            "    }",
            f"    return qvariant_cast<{ret}>(result);",
        ]
    body = "\n".join(lines)
    return f"{head}\n{{\n{body}\n}}"


# ----------------------------------------------------------------- consumer side
#
# The consumer facade is what the accessor family (Server, Database, ...) exposes for a
# consumed connect point: it forwards the Replica's push properties, models and signals,
# turns a returning slot into a Promise (`slot(args).then(...)`), and publishes itself to
# the ConnectPointResolver so `<Contract>.on<Signal>` attached handlers find it. It is
# Replica-type agnostic (it reflects through the metaobject), so one facade serves a typed
# Replica on the client and a dynamic Replica on the mesh. Everything is guarded on the
# runtime's <consumerbase.h>, so a Replica-only target compiles it away to nothing.


def _types_csv(params, records, path) -> str:
    return ",".join(
        cpp_type(param.type, records, path=path, line=param.line, col=param.col)
        for param in params
    )


def _qarg_suffix(params, records, path) -> str:
    terms = [
        "Q_ARG(%s, %s)"
        % (cpp_type(param.type, records, path=path, line=param.line, col=param.col), param.name)
        for param in params
    ]
    return "".join(", " + term for term in terms)


def emit_consumer_header(syn: SynFile, lstem: str) -> str:
    out: List[str] = [SPDX_CPP, "#pragma once", ""]
    out += ["#if __has_include(<consumerbase.h>)",
            "#  include <consumerbase.h>",
            "#  include <promise.h>", "",
            f'#  include "{lstem}_rep.h"', "",
            "#  include <QtQml/qqmlregistration.h>", "",
            "#  include <QAbstractItemModel>",
            "#  include <QList>",
            "#  include <QObject>",
            "#  include <QString>", ""]
    records = syn.record_names
    path = f"{syn.stem}.syn"
    for contract in syn.contracts:
        out.append(_consumer_class(contract, records, path))
        out.append("")
        out.append(_attached_classes(contract, records, path))
        out.append("")
    out.append("#endif")
    out.append("")
    out.append(f"void synqtRegister{_cap(syn.stem)}Consumers();")
    out.append("")
    return "\n".join(out)


def _consumer_class(contract: Contract, records, path) -> str:
    name = contract.name
    lines = [
        f"// Consumer facade for {name}: the live accessor entry (Server.<name> or",
        f"// <Owner>.<name>) for a consumed {name} connect point.",
        f"class {name}Consumer : public SynQt::ConsumerBase",
        "{",
        "    Q_OBJECT",
        "    Q_PROPERTY(bool ready READ isReady NOTIFY readyChanged)",
    ]
    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines.append(
            f"    Q_PROPERTY({ctype} {prop.name} READ {prop.name} NOTIFY {prop.name}Changed)")
    for model in contract.models:
        lines.append(
            f"    Q_PROPERTY(QAbstractItemModel *{model.name} READ {model.name} "
            f"NOTIFY {model.name}Changed)")
    lines += [
        "",
        "public:",
        f"    explicit {name}Consumer(QObject *parent = nullptr);",
        "",
        "    QString contractName() const override;",
        "",
    ]
    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines.append(f"    {ctype} {prop.name}() const;")
    for model in contract.models:
        lines.append(f"    QAbstractItemModel *{model.name}() const;")
    if contract.props or contract.models:
        lines.append("")
    for slot in contract.slots:
        params = _param_list(slot.params, records, path)
        if slot.return_type is None:
            lines.append(f"    Q_INVOKABLE void {slot.name}({params});")
        else:
            lines.append(f"    Q_INVOKABLE SynQt::Promise *{slot.name}({params});")
    if contract.slots:
        lines.append("")
    lines.append("signals:")
    for prop in contract.props:
        lines.append(f"    void {prop.name}Changed();")
    for model in contract.models:
        lines.append(f"    void {model.name}Changed();")
    for signal in contract.signals:
        params = _param_list(signal.params, records, path)
        lines.append(f"    void {signal.name}({params});")
    lines += [
        "",
        "protected:",
        "    void bindReplica() override;",
        "    void emitAllChanged() override;",
        "};",
    ]
    return "\n".join(lines)


def _attached_classes(contract: Contract, records, path) -> str:
    name = contract.name
    lines = [
        f"// The `{name}.on<Signal>` attached type: no target, it resolves the {name} connect",
        "// point this entity consumes (disambiguated by `.point`) and relays its signals.",
        f"class {name}Attached : public QObject",
        "{",
        "    Q_OBJECT",
        "    Q_PROPERTY(QString point READ point WRITE setPoint NOTIFY pointChanged)",
        "",
        "public:",
        f"    explicit {name}Attached(QObject *parent = nullptr);",
        "",
        "    QString point() const;",
        "    void setPoint(const QString &point);",
        "",
        "signals:",
    ]
    for signal in contract.signals:
        params = _param_list(signal.params, records, path)
        lines.append(f"    void {signal.name}({params});")
    lines += [
        "    void pointChanged();",
        "",
        "private:",
        "    void rebind();",
        "",
        "    QString m_point;",
        "    QObject *m_consumer{nullptr};",
        "    QList<QMetaObject::Connection> m_connections;",
        "};",
        "",
        f"// The attaching type registered as the QML name \"{name}\", so `{name}.on<Signal>`",
        "// resolves. It does nothing but provide the attached object.",
        f"class {name} : public QObject",
        "{",
        "    Q_OBJECT",
        f"    QML_ATTACHED({name}Attached)",
        "",
        "public:",
        f"    explicit {name}(QObject *parent = nullptr) : QObject{{parent}} {{}}",
        "",
        f"    static {name}Attached *qmlAttachedProperties(QObject *object)",
        f"    {{ return new {name}Attached{{object}}; }}",
        "};",
    ]
    return "\n".join(lines)


CONSUMER_RELAY_HELPER = """namespace {
// Relay one signal to another by signature, tolerating a Replica that does not expose it
// (a dynamic Replica has no model-changed property signal): connect only when both exist,
// so nothing warns. Returns the connection so the facade can drop it on the next rebind.
QMetaObject::Connection synqtRelay(QObject *from, const QByteArray &fromSignal,
                                   QObject *to, const QByteArray &toSignal)
{
    const QMetaObject *fromMeta{from->metaObject()};
    const QMetaObject *toMeta{to->metaObject()};
    const int fromIndex{fromMeta->indexOfSignal(
        QMetaObject::normalizedSignature(fromSignal.constData()).constData())};
    const int toIndex{toMeta->indexOfSignal(
        QMetaObject::normalizedSignature(toSignal.constData()).constData())};
    if (fromIndex < 0 || toIndex < 0) {
        return QMetaObject::Connection{};
    }
    return QObject::connect(from, fromMeta->method(fromIndex), to, toMeta->method(toIndex));
}
} // namespace
"""


def emit_consumer_source(syn: SynFile, lstem: str) -> str:
    out: List[str] = [SPDX_CPP, f'#include "{lstem}_consumer.h"', "", "#if __has_include(<consumerbase.h>)"]
    out += ['#  include "connectpointresolver.h"',
            '#  include "consumerfactory.h"', "",
            "#  include <QJSEngine>",
            "#  include <QMetaMethod>",
            "#  include <QMetaObject>",
            "#  include <QtQml/qqmlengine.h>",
            "#  include <QtRemoteObjects/QRemoteObjectPendingReply>",
            "#  include <QVariant>", ""]
    out.append(CONSUMER_RELAY_HELPER)
    records = syn.record_names
    path = f"{syn.stem}.syn"
    for contract in syn.contracts:
        out.append(_consumer_impl(contract, records, path))
        out.append("")
        out.append(_attached_impl(contract, records, path))
        out.append("")
    out.append(f"void synqtRegister{_cap(syn.stem)}Consumers()")
    out.append("{")
    for contract in syn.contracts:
        out.append(
            f'    SynQt::registerConsumerFactory(QStringLiteral("{contract.name}"),')
        out.append(
            f"        []() -> SynQt::ConsumerBase * {{ return new {contract.name}Consumer{{}}; }});")
        out.append(
            f'    qmlRegisterType<{contract.name}>("SynQt", 1, 0, "{contract.name}");')
    out.append("}")
    out.append("#else")
    out.append(f"void synqtRegister{_cap(syn.stem)}Consumers() {{}}")
    out.append("#endif")
    out.append("")
    return "\n".join(out)


def _consumer_impl(contract: Contract, records, path) -> str:
    name = contract.name
    cls = f"{name}Consumer"
    lines: List[str] = [
        f"{cls}::{cls}(QObject *parent)",
        f"    : SynQt::ConsumerBase{{parent}}",
        "{",
        "}",
        "",
        f"QString {cls}::contractName() const",
        "{",
        f'    return QStringLiteral("{name}");',
        "}",
        "",
    ]

    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines += [
            f"{ctype} {cls}::{prop.name}() const",
            "{",
            "    if (m_replica == nullptr) {",
            f"        return {ctype}{{}};",
            "    }",
            f'    return qvariant_cast<{ctype}>(m_replica->property("{prop.name}"));',
            "}",
            "",
        ]

    for model in contract.models:
        lines += [
            f"QAbstractItemModel *{cls}::{model.name}() const",
            "{",
            "    if (m_replica == nullptr) {",
            "        return nullptr;",
            "    }",
            "    return qobject_cast<QAbstractItemModel *>(",
            f'        qvariant_cast<QObject *>(m_replica->property("{model.name}")));',
            "}",
            "",
        ]

    for slot in contract.slots:
        lines.append(_consumer_slot_impl(name, slot, records, path))
        lines.append("")

    # bindReplica: (re)wire the property, model and signal relays from the Replica.
    lines += [f"void {cls}::bindReplica()", "{"]
    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines.append(
            f'    addConnection(synqtRelay(m_replica, "{prop.name}Changed({ctype})",')
        lines.append(
            f'                             this, "{prop.name}Changed()"));')
    for model in contract.models:
        lines.append(
            f'    addConnection(synqtRelay(m_replica,'
            f' "{model.name}Changed(QAbstractItemModelReplica*)",')
        lines.append(
            f'                             this, "{model.name}Changed()"));')
    for signal in contract.signals:
        types = _types_csv(signal.params, records, path)
        lines.append(
            f'    addConnection(synqtRelay(m_replica, "{signal.name}({types})",')
        lines.append(
            f'                             this, "{signal.name}({types})"));')
    if not (contract.props or contract.models or contract.signals):
        lines.append("    // No push properties, models or signals to relay.")
    lines += ["}", ""]

    lines += [f"void {cls}::emitAllChanged()", "{"]
    for prop in contract.props:
        lines.append(f"    emit {prop.name}Changed();")
    for model in contract.models:
        lines.append(f"    emit {model.name}Changed();")
    if not (contract.props or contract.models):
        lines.append("    // No push properties or models to re-notify.")
    lines.append("}")
    return "\n".join(lines)


def _consumer_slot_impl(class_name: str, slot: Slot, records, path) -> str:
    cls = f"{class_name}Consumer"
    params = _param_list(slot.params, records, path)
    qargs = _qarg_suffix(slot.params, records, path)
    if slot.return_type is None:
        return "\n".join([
            f"void {cls}::{slot.name}({params})",
            "{",
            "    if (m_replica == nullptr) {",
            "        return;",
            "    }",
            f'    QMetaObject::invokeMethod(m_replica, "{slot.name}"{qargs});',
            "}",
        ])
    ret = cpp_type(slot.return_type, records, path=path, line=slot.line, col=slot.col)
    # Both a typed Replica and a dynamic Replica expose a returning slot as a meta-method
    # that returns QRemoteObjectPendingReply<T> with the concrete T, so one typed return arg
    # captures either (QRemoteObjectPendingReply<T> is-a QRemoteObjectPendingCall).
    return "\n".join([
        f"SynQt::Promise *{cls}::{slot.name}({params})",
        "{",
        "    QJSEngine *engine{qjsEngine(this)};",
        "    if (m_replica == nullptr) {",
        f'        return SynQt::Promise::rejected(QStringLiteral("the \'{class_name}\' connect '
        'point is not available"), engine, this);',
        "    }",
        f"    QRemoteObjectPendingReply<{ret}> reply;",
        f'    QMetaObject::invokeMethod(m_replica, "{slot.name}",',
        f"                              Q_RETURN_ARG(QRemoteObjectPendingReply<{ret}>,"
        f" reply){qargs});",
        "    return new SynQt::Promise{reply, engine, this};",
        "}",
    ])


def _attached_impl(contract: Contract, records, path) -> str:
    name = contract.name
    cls = f"{name}Attached"
    lines = [
        f"{cls}::{cls}(QObject *parent)",
        "    : QObject{parent}",
        "{",
        "    connect(SynQt::ConnectPointResolver::instance(),",
        "            &SynQt::ConnectPointResolver::changed, this,",
        "            [this](const QString &contract) {",
        f'                if (contract == QStringLiteral("{name}")) {{',
        "                    rebind();",
        "                }",
        "            });",
        "    rebind();",
        "}",
        "",
        f"QString {cls}::point() const",
        "{",
        "    return m_point;",
        "}",
        "",
        f"void {cls}::setPoint(const QString &point)",
        "{",
        "    if (m_point == point) {",
        "        return;",
        "    }",
        "    m_point = point;",
        "    emit pointChanged();",
        "    rebind();",
        "}",
        "",
        f"void {cls}::rebind()",
        "{",
        "    QObject *consumer{SynQt::ConnectPointResolver::instance()->resolve(",
        f'        QStringLiteral("{name}"), m_point)}};',
        "    if (consumer == m_consumer) {",
        "        return;",
        "    }",
        "    for (const QMetaObject::Connection &connection : std::as_const(m_connections)) {",
        "        disconnect(connection);",
        "    }",
        "    m_connections.clear();",
        "    m_consumer = consumer;",
        "    if (m_consumer == nullptr) {",
        "        return;",
        "    }",
    ]
    for signal in contract.signals:
        types = _types_csv(signal.params, records, path)
        lines.append(
            f'    m_connections.append(synqtRelay(m_consumer, "{signal.name}({types})",')
        lines.append(
            f'                                    this, "{signal.name}({types})"));')
    if not contract.signals:
        lines.append("    // The contract declares no signals to relay.")
    lines.append("}")
    return "\n".join(lines)


# ------------------------------------------------------------------ replica side


def emit_replica_header(syn: SynFile, lstem: str) -> str:
    return "\n".join([SPDX_CPP, "#pragma once", "",
                      f"void synqtRegister{_cap(syn.stem)}Replicas();", ""])


def emit_replica_source(syn: SynFile, lstem: str) -> str:
    out = [SPDX_CPP,
           f'#include "{lstem}_replica.h"', "",
           f'#include "{lstem}_rep.h"', "",
           "#include <QQmlEngine>", "",
           "// When this Replica is built into a client that links the SynQt client runtime,"
           " register a",
           "// typed-Replica factory: a compile-time Replica carries its API and so syncs"
           " reliably,",
           "// including in the browser (a dynamic Replica's API-definition exchange does"
           " not complete",
           "// under single-threaded WASM). A minimal replica-only target that does not link"
           " the",
           "// runtime simply skips this and still builds.",
           "#if __has_include(<replicaregistry.h>)",
           "#  include <QRemoteObjectNode>",
           "#  include <replicaregistry.h>",
           "#  define SYNQT_REPLICA_FACTORY 1",
           "#endif", "",
           f"void synqtRegister{_cap(syn.stem)}Replicas()",
           "{"]
    for contract in syn.contracts:
        out.append(
            f'    qmlRegisterUncreatableType<{contract.name}Replica>("SynQt", 1, 0,'
        )
        out.append(
            f'        "{contract.name}Replica",'
        )
        out.append(
            f'        QStringLiteral("{contract.name}Replica is acquired from the SynQt '
            'runtime, not constructed in QML"));'
        )
        out.append("#ifdef SYNQT_REPLICA_FACTORY")
        out.append(
            f'    SynQt::registerReplicaFactory(QStringLiteral("{contract.name}"),'
        )
        out.append(
            "        [](QRemoteObjectNode *node, const QString &connectPoint) -> QObject * {"
        )
        out.append(
            f"            return node->acquire<{contract.name}Replica>(connectPoint);"
        )
        out.append("        });")
        out.append("#endif")
    out.append("}")
    out.append("")
    return "\n".join(out)
