# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Lower a parsed :class:`SynFile` to the generated C++/rep artifacts.

Three outputs per contract file:

* the ``.rep`` (records -> POD, prop -> PROP READPUSH, model -> MODEL with only its
  declared roles, signal -> SIGNAL, slot -> SLOT with the return type when present);
* the owner-side Source helper (``<Contract>Source`` in QML), whose
  ``set<Model>(rows)`` keeps only declared roles and drops undeclared row fields;
* the consumer-side Replica QML registration.
"""

from __future__ import annotations

from typing import List

from .model import Contract, Model, Signal, Slot, SynFile
from .types import base_of, bound_of, cpp_type, is_generic, measure, unit_of

SPDX_CPP = (
    "// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux\n"
    "// SPDX-License-Identifier: Apache-2.0\n"
    "// Generated by synqtc from a .syn contract. Do not edit.\n"
)


#: The extra leading argument every slot takes on a contract a service consumes: the
#: session the calling entity is acting for. Written in one place, because the rep, the
#: owner-side override and the consumer's invoke all have to spell it the same way.
SESSION_PARAM = "QVariantMap synqtSession"
SESSION_ARG = "synqtSession"


def _cap(name: str) -> str:
    return name[:1].upper() + name[1:]


def _gate(member) -> List[str]:
    """The scopes that reach `member`, empty when everyone the point is hosted for does."""
    return list(getattr(member, "scope", None) or [])


def _gate_literal(scopes: List[str]) -> str:
    return "QStringList{" + ", ".join(f'QStringLiteral("{name}")' for name in scopes) + "}"


def _is_gated(contract: Contract) -> bool:
    return any(_gate(member) for member in contract.members)


def _gated_props(contract: Contract):
    return [prop for prop in contract.props if _gate(prop)]


def _slot_params(syn: SynFile, slot, records, path) -> str:
    """A slot's parameter list as it is declared, session first when there is one."""
    declared = [f"{cpp_type(p.type, records, path=path, line=p.line, col=p.col)} {p.name}"
                for p in slot.params]
    if syn.forwards_session:
        declared.insert(0, SESSION_PARAM)
    return ", ".join(declared)


def _slot_args(syn: SynFile, slot) -> str:
    """A slot's arguments as they are passed on, session first when there is one."""
    passed = [param.name for param in slot.params]
    if syn.forwards_session:
        passed.insert(0, SESSION_ARG)
    return ", ".join(passed)


def _param_list(params, record_names, path) -> str:
    return ", ".join(
        f"{cpp_type(param.type, record_names, path=path, line=param.line, col=param.col)} {param.name}"
        for param in params
    )


# What a declared bound is worth at run time
#
# A bound written in a contract (`string[64]`, `list[100]`, `var[4096]`) is a rule about
# what may cross, so the generated boundary enforces it rather than describing it. A value
# that breaks the rule is refused and named in a warning; nothing is quietly truncated into
# something that looks right, because a silently shortened name and a silently dropped tail
# are exactly the bugs a bound exists to prevent.

#: The QtCore header a contract type needs. repc copies single-line directives from the
#: top of a `.rep` into the header it generates, and its own includes stop at qvariant.h,
#: so a contract that names a date or a URL says so there.
TYPE_INCLUDES = {
    "date": "QDateTime",
    "list": "QVariantList",
    "string": "QString",
    "url": "QUrl",
    "var": "QVariant",
    "variant": "QVariant",
}


def _bound_guard(spelling: str, value: str, where: str, field: str,
                 refuse: List[str], indent: str) -> List[str]:
    """Refuse `value` when it is over the bound its type was written with.

    `value` is an expression already of the type's C++ spelling, because how a value is
    measured depends on what it is: characters for text, elements for a list, and for a
    `var` the bytes it serializes to, which is the only honest answer to how big something
    generic is.
    """
    bound = bound_of(spelling)
    size = measure(spelling, value)
    if bound is None or size is None:
        return []
    unit = unit_of(spelling)
    guard = [
        f"const qsizetype {field}Size{{{size}}};",
        f"if ({field}Size > {bound}) {{",
        f'    qWarning("%s: \'%s\' is declared %s and the value is %lld {unit}; '
        'refused",',
        f'             "{where}", "{field}", "{spelling}",'
        f" static_cast<long long>({field}Size));",
    ] + [f"    {line}" for line in refuse] + ["}"]
    return [indent + line for line in guard]


def _written_types(syn: SynFile) -> List[str]:
    """Every type spelling the file writes, in no particular order."""
    written: List[str] = []
    for record in syn.records:
        written += [field.type for field in record.fields]
    for contract in syn.contracts:
        written += [prop.type for prop in contract.props]
        for model in contract.models:
            written += [role.type for role in model.roles]
        for signal in contract.signals:
            written += [param.type for param in signal.params]
        for slot in contract.slots:
            written += [param.type for param in slot.params]
            if slot.return_type is not None:
                written.append(slot.return_type)
    return written


def _type_includes(syn: SynFile) -> List[str]:
    """The Qt headers this file's types need, as `.rep` directives, sorted."""
    needed = {TYPE_INCLUDES[base_of(written)] for written in _written_types(syn)
              if base_of(written) in TYPE_INCLUDES}
    if syn.forwards_session and any(contract.slots for contract in syn.contracts):
        needed.add("QVariantMap")
    return sorted(needed)


def _bounds_a_var(syn: SynFile) -> bool:
    """Does anything here bound a `var`, and so need the serialized-size helper?"""
    return any(is_generic(written) and bound_of(written) is not None
               for written in _written_types(syn))


# `import SynQt` re-exports QtQuick, so an entity's QML writes one import line and leans on
# Item, Timer and Component.onCompleted without naming QtQuick. The re-export is a call, and
# it used to be one only the generated entity main made: any other host of the same QML - a
# test harness, an embedder, a tool loading one Source - registered the contract, loaded the
# file, and got "Timer is not a type". Registering the contract is the one thing every such
# host does, so the re-export rides along with it. Idempotent, so an entity with several
# contracts still installs it once.
MODULE_IMPORTS_INCLUDE = """// Present whenever a runtime is linked, absent for a contract-only target, which has no
// engine to make the re-export mean anything; the call below is guarded the same way.
#if __has_include(<moduleimports.h>)
#  include <moduleimports.h>
#  define SYNQT_HAS_MODULE_IMPORTS 1
#endif"""

MODULE_IMPORTS_CALL = """#ifdef SYNQT_HAS_MODULE_IMPORTS
    // Registering a contract is what makes `import SynQt` enough: it brings QtQuick with it,
    // so the QML registered just below can hold a Timer without a second import line.
    SynQt::registerModuleImports();
#endif"""

ACTING_FOR_SHIM = """// A slot names the Caller it is answering for as long as it runs, so that a call the
// owner's implementation makes on to another entity carries the same person. That lives in
// the consumer runtime, which a contract-only target does not link and has nothing to call
// out to either, so there it is a name that does nothing.
#if __has_include(<actingfor.h>)
#  include <actingfor.h>
using SynqtActingFor = SynQt::ActingFor;
namespace {
QVariantMap synqtActingForSession() { return SynQt::ActingFor::current(); }
} // namespace
#else
namespace {
struct SynqtActingFor
{
    explicit SynqtActingFor(QObject *) {}
    ~SynqtActingFor() = default;
};
QVariantMap synqtActingForSession() { return QVariantMap{}; }
} // namespace
#endif
"""
CALL_SPAN_SHIM = """// Every slot call crossing a link is timed and recorded, however it leaves: refused by a
// scope gate, refused by a bound on an argument, forwarded to the entity behind a front,
// or answered by the owner's own QML. The record is closed by the destructor rather than
// by a line before each return, so a return added here later stays traced.
//
// It records the shape of the call and never its arguments, which are what a person
// typed. The whole thing lives in the service runtime; a contract-only target links no
// runtime, has nothing to record to, and compiles the same slot bodies against a span
// that does nothing at all.
#if __has_include(<callspan.h>)
#  include <callspan.h>
using SynqtCallSpan = SynQt::CallSpan;
#else
namespace {
class SynqtCallSpan
{
public:
    SynqtCallSpan(const char *, const char *, QObject *, int) {}
    ~SynqtCallSpan() {}
    void refuse(const char *) {}
    void fail(const char *) {}
};
} // namespace
#endif
"""


VARIANT_BYTES_HELPER = """namespace {
// What a var costs on the wire. `var[n]` bounds a value whose type says nothing about how
// big it is, so the only measure that means anything is what it serializes to, and that is
// measured rather than estimated.
qsizetype synqtVariantBytes(const QVariant &value)
{
    QByteArray buffer;
    QDataStream stream{&buffer, QIODevice::WriteOnly};
    stream << value;
    return buffer.size();
}
} // namespace
"""


# rep


def emit_rep(syn: SynFile) -> str:
    records = syn.record_names
    path = f"{syn.stem}.syn"
    lines: List[str] = [SPDX_CPP.rstrip("\n"), ""]

    # repc copies these into the header it generates, ahead of the declarations that need
    # them. Without them a contract naming a date or a URL compiles only by the luck of
    # something else having included it first.
    includes = _type_includes(syn)
    if includes:
        lines += [f"#include <{header}>" for header in includes]
        lines.append("")

    for record in syn.records:
        fields = ", ".join(
            f"{cpp_type(f.type, records, path=path, line=f.line, col=f.col)} {f.name}"
            for f in record.fields
        )
        lines.append(f"POD {record.name}({fields})")
    if syn.records:
        lines.append("")

    for contract in syn.contracts:
        lines.append(f"class {contract.name}")
        lines.append("{")
        for member in contract.members:
            lines.append("    " + _lower_member(syn, member, records, path))
        lines.append("}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def _lower_member(syn: SynFile, member, records, path) -> str:
    if isinstance(member, Model):
        # repc's roles are names. The declared types are ours to enforce, at the
        # publish boundary in the Source helper.
        return f"MODEL {member.name}({', '.join(role.name for role in member.roles)})"
    if isinstance(member, Signal):
        return f"SIGNAL({member.name}({_param_list(member.params, records, path)}))"
    if isinstance(member, Slot):
        params = _slot_params(syn, member, records, path)
        if member.return_type is None:
            return f"SLOT(void {member.name}({params}))"
        ret = cpp_type(member.return_type, records, path=path, line=member.line, col=member.col)
        return f"SLOT({ret} {member.name}({params}))"
    # Prop: READPUSH is the SynQt default and is written explicitly for clarity.
    ctype = cpp_type(member.type, records, path=path, line=member.line, col=member.col)
    return f"PROP({ctype} {member.name} READPUSH)"


# source side


def _has_models(syn: SynFile) -> bool:
    return any(contract.models for contract in syn.contracts)


def emit_source_helper_header(syn: SynFile, lstem: str) -> str:
    # <lstem>_rep.h is an indirection the build writes to the correct repc header for
    # this target's role (_source, _replica, or _merged), so the helper compiles the
    # same way whether the target is an owner or a both-sided test.
    out: List[str] = [SPDX_CPP, "#pragma once", "",
                      f'#include "{lstem}_rep.h"', "",
                      "#include <QList>",
                      "#include <QObject>",
                      "#include <QPointer>",
                      "#include <QQmlListProperty>", ""]
    # SourceModel is a QStandardItemModel that refuses a write arriving from a consumer,
    # and it is QtGui through its base; only pull it in when a contract actually has a
    # model, so a model-less service does not need QtGui.
    if _has_models(syn):
        out += ["#include <sourcemodel.h>", "#include <QVariantList>", ""]
    records = syn.record_names
    path = f"{syn.stem}.syn"
    for contract in syn.contracts:
        out.append(_source_helper_class(syn, contract, records, path))
        out.append("")
    # The typed Caller subclass (emit<Signal> sugar) is only meaningful when this Source is
    # hosted by the service runtime, which is the only thing that binds a Caller. Guard it on
    # the runtime's caller.h so a standalone contract target (rep-only) still compiles.
    caller_subclasses = [_caller_subclass(contract, records, path)
                         for contract in syn.contracts if contract.signals]
    if caller_subclasses:
        out += ["#if __has_include(<caller.h>)",
                "#  include <caller.h>", "", "#  include <QVariant>", ""]
        out += caller_subclasses
        out += ["#endif", ""]
    out.append(f"void synqtRegister{_cap(syn.stem)}Sources();")
    out.append("")
    return "\n".join(out)


def _caller_subclass(contract: Contract, records, path) -> str:
    # A per-contract Caller whose emit<Signal>(...) methods forward to the inherited
    # emitSignal, giving owner QML the Caller.emit<Signal>(...) sugar (e.g.
    # Caller.emitRejected(reason)). The per-connection Source has a single consumer, so the
    # signal reaches this caller alone.
    name = contract.name
    lines = [
        f"// Typed Caller for {name}: Caller.emit<Signal>(...) sugar over emitSignal.",
        f"class {name}Caller : public SynQt::Caller",
        "{",
        "    Q_OBJECT",
        "",
        "public:",
        f"    explicit {name}Caller(QObject *parent = nullptr) : SynQt::Caller{{parent}} {{}}",
        "",
    ]
    for signal in contract.signals:
        params = _param_list(signal.params, records, path)
        variants = "".join(", QVariant::fromValue(%s)" % p.name for p in signal.params)
        lines.append(
            f"    Q_INVOKABLE void emit{_cap(signal.name)}({params})")
        lines.append(
            f'    {{ emitSignal(QStringLiteral("{signal.name}"){variants}); }}')
    lines.append("};")
    return "\n".join(lines)


def _source_helper_class(syn: SynFile, contract: Contract, records, path) -> str:
    name = contract.name
    lines = [
        "// Owner-side helper: the QML type the connect point's server file derives",
        f"// from (registered as \"{name}\", the contract's own name: the file is that",
        "// point's server, so its location already says which side of the link it is on,",
        "// and an entity never consumes a contract it owns, so the name is free here).",
        "// Props and signals are inherited from the generated Source. A model is published",
        "// either way round: bind <model>Rows to where the rows live, or call",
        "// set<Model>(rows) when something happens. Both keep only the declared roles,",
        "// dropping any undeclared owner-only field at the boundary.",
        f"class {name}SourceHelper : public {name}SimpleSource",
        "{",
        "    Q_OBJECT",
        "    // A generated Source is not a visual item, so its default property is a plain",
        "    // QObject child list: this lets the owner's server file declare non-visual QML",
        "    // children (a Timer, an Instantiator, ...) inside the Source to drive itself.",
        '    Q_CLASSINFO("DefaultProperty", "data")',
        "    Q_PROPERTY(QQmlListProperty<QObject> data READ data DESIGNABLE false)",
    ]
    if contract.models:
        # The declarative way to publish a model: bind `<model>Rows` to whatever holds the
        # rows (usually a list on the entity's own singleton) and every change to it
        # republishes. Without it an owner had to call set<Model>(rows) from
        # Component.onCompleted and again from a Connections block watching the singleton,
        # which is three lines of bookkeeping saying what one binding says.
        #
        # A name of its own rather than the model's: the generated Source already carries
        # `Q_PROPERTY(QAbstractItemModel *<model> ...)`, and QtRO resolves that property by
        # name off the most derived meta-object (qtro_property_index calls
        # indexOfProperty), so a property here with the same name would be the one it tried
        # to remote as the model.
        lines.append("")
        for model in contract.models:
            lines.append(f"    Q_PROPERTY(QVariantList {model.name}Rows READ {model.name}Rows")
            lines.append(f"               WRITE set{_cap(model.name)}Rows"
                         f" NOTIFY {model.name}RowsChanged)")
    lines += [
        "",
        "public:",
        f"    explicit {name}SourceHelper(QObject *parent = nullptr);",
        "",
        "    QQmlListProperty<QObject> data();",
        "",
        "    // Shared entities. An entity that is shared answers everyone from one Source,",
        "    // and each caller reaches it through a mirror: the mirror is what that caller's",
        "    // links acquire, it republishes the shared Source's props, models and signals",
        "    // outward, and it forwards every slot back with that caller bound. Both calls",
        "    // are the runtime's, invoked by name so it needs none of these types.",
        "    Q_INVOKABLE void synqtSetCaller(QObject *caller);",
        "    Q_INVOKABLE void synqtMirror(QObject *shared);",
        "",
    ]
    lines += [
        "    // Fronts. A web edge may own a point it does not implement and hand each",
        "    // caller to the entity serving their scope; this Source is what the browser",
        "    // acquires, and `replica` is that entity. Everything it publishes is followed",
        "    // outward and every slot is forwarded back, so the caller sees one surface and",
        "    // never learns which of them answered. The runtime calls this by name.",
        "    Q_INVOKABLE void synqtRelay(QObject *replica);",
        "",
    ]
    lines += [
            "    // Scope gates. A member written `<admin> ...` in the contract reaches only",
            "    // a caller holding that scope, and the gate is on what crosses rather than",
            "    // on the shape: the member is still declared, so a Replica still matches by",
            "    // signature, and nothing about it is ever published or accepted for a caller",
            "    // without the scope. This instance gates by default, which is what a mirror",
            "    // and a per-caller Source both want; the one Source a shared entity answers",
            "    // everyone from holds the ungated truth its mirrors publish from, and the",
            "    // runtime says so by calling this.",
            "    Q_INVOKABLE void synqtHoldsSharedState();",
            "",
            "public Q_SLOTS:",
            "    // Publish every gated member again, now that this caller's scope has",
            "    // changed. What they may not see is withdrawn, not left where it was.",
            "    void synqtRegate();",
            "",
            "public:",
            "",
        ]
    # One slots block, holding everything a QMetaMethod has to be able to connect to: the
    # pull slots a front follows the entity behind it with, and the emit<Signal> methods a
    # mirror and a front both relay a broadcast into. Q_INVOKABLE is not enough for either,
    # because QObject::connect refuses a target that is not a slot or a signal.
    followed = contract.props + contract.models
    if followed or contract.signals:
        lines.append("public Q_SLOTS:")
    for member in followed:
        lines.append(f"    void synqtPull{_cap(member.name)}();")
    if followed and contract.signals:
        lines.append("")
    if contract.signals:
        lines.append("    // Deliver a contract signal to the acquiring consumer(s). On a")
        lines.append("    // one Source per caller the sole consumer is that caller, so")
        lines.append("    // Caller.emitSignal(\"<Signal>\", ...) routes here to answer one caller.")
        for signal in contract.signals:
            params = _param_list(signal.params, records, path)
            lines.append(f"    void emit{_cap(signal.name)}({params});")
    if followed or contract.signals:
        lines += ["", "public:", ""]
    if contract.models:
        # repc gives the Source a virtual set<Model>(QAbstractItemModel *) that the
        # owner is not meant to call: the model it publishes is this class's own. The
        # `using` keeps that overload visible all the same, because a name declared
        # here would otherwise hide it, and a hidden virtual is a warning every
        # translation unit that includes this header has to carry.
        for model in contract.models:
            lines.append(f"    using {name}SimpleSource::set{_cap(model.name)};")
        for model in contract.models:
            lines.append(
                f"    Q_INVOKABLE void set{_cap(model.name)}(const QVariantList &rows);")
        lines.append("")
        # The rows last published, so the bindable property has something to read back.
        # A QVariantList copy is a reference count, so holding the rows the owner handed
        # over costs nothing until one side changes them.
        for model in contract.models:
            lines.append(f"    QVariantList {model.name}Rows() const "
                         f"{{ return m_{model.name}Rows; }}")
            lines.append(f"    void set{_cap(model.name)}Rows(const QVariantList &rows) "
                         f"{{ set{_cap(model.name)}(rows); }}")
        lines.append("")
    bounded = _intercepted_props(contract)
    if bounded:
        lines.append("    // Bounded and gated props. repc makes every setter virtual, so both")
        lines.append("    // are kept here: an assignment that breaks a bound is refused and")
        lines.append("    // named, and one the caller has no scope for is remembered but not")
        lines.append("    // published, so what the Source pushes is always inside the contract")
        lines.append("    // and always something this caller may see.")
        for prop in bounded:
            ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
            lines.append(f"    void set{_cap(prop.name)}({ctype} {prop.name}) override;")
        lines.append("")
    if contract.slots:
        lines.append("    // Consumer -> owner requests. Each dispatches to the owner's QML")
        lines.append("    // implementation (a QML function of the same name); a slot the owner")
        lines.append("    // did not implement is a no-op (or returns a default).")
        for slot in contract.slots:
            lines.append("    " + _slot_signature(syn, slot, records, path) + " override;")
        lines.append("")

    if contract.models:
        lines.append("Q_SIGNALS:")
        for model in contract.models:
            lines.append(f"    void {model.name}RowsChanged();")
        lines.append("")
    lines.append("private:")
    lines.append("    static void appendData(QQmlListProperty<QObject> *list, QObject *object);")
    lines.append("    // Make the shared Source's Caller be whoever is calling right now.")
    lines.append("    void synqtAdoptCaller(QObject *caller);")
    if _is_gated(contract):
        lines.append("    // Does the caller this Source answers hold any of these scopes?")
        lines.append("    // False when there is no caller at all, so a gate fails closed.")
        lines.append("    bool synqtAllows(const QStringList &scopes) const;")
    lines.append("")
    lines.append("    QList<QObject *> m_data;")
    lines.append("    QPointer<QObject> m_synqtCaller;")
    lines.append(f"    QPointer<{name}SourceHelper> m_synqtShared;")
    lines.append("    // The entity behind a front, when this Source is one caller's view of it.")
    lines.append("    QPointer<QObject> m_synqtRelay;")
    if contract.slots:
        lines.append("    bool m_synqtRelayTakesSession{false};")
    lines.append("    bool m_synqtUngated{false};")
    for prop in _gated_props(contract):
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        # What the owner last assigned, kept apart from what the Source publishes: a gate
        # that opens later has to have something to publish, and one that closes has to be
        # able to withdraw without losing the value it was hiding.
        lines.append(f"    {ctype} m_synqt{_cap(prop.name)}{{}};")
    for model in contract.models:
        lines.append(f"    SynQt::SourceModel m_{model.name}Model;")
        lines.append(f"    QVariantList m_{model.name}Rows;")
    lines.append("};")
    return "\n".join(lines)


def _slot_signature(syn: SynFile, slot: Slot, records, path) -> str:
    params = _slot_params(syn, slot, records, path)
    if slot.return_type is None:
        return f"void {slot.name}({params})"
    ret = cpp_type(slot.return_type, records, path=path, line=slot.line, col=slot.col)
    return f"{ret} {slot.name}({params})"


SLOT_DISPATCH_HELPER = """namespace {
// Dispatch a consumer's slot call to the owner's QML implementation. A QML `function`
// with the slot's name is added to the object's meta-object beyond the generated
// helper's own C++ methods (cppMethodCount); if one exists, this returns its index so
// the slot can invoke it. Returns -1 when the owner did not implement the slot in QML,
// in which case the slot is a no-op (or returns a default), never recursing into itself.
int synqtQmlSlotIndex(const QObject *object, const char *name, int paramCount,
                      int cppMethodCount)
{
    const QMetaObject *metaObject{object->metaObject()};
    for (int index{metaObject->methodCount() - 1}; index >= cppMethodCount; --index) {
        const QMetaMethod method{metaObject->method(index)};
        if (method.name() == name && method.parameterCount() == paramCount) {
            return index;
        }
    }
    return -1;
}
} // namespace
"""


RELAY_INTRO = """namespace {
// Wiring for a front: a web edge that owns a point it does not implement and hands each
// caller to the entity serving their scope. The Source the browser acquires is this
// helper, and what answers it is a Replica of a different contract, so everything here
// goes through the meta-object by name. That is also what keeps it free of any SynQt
// header, the way the rest of this file is: a contract target linking no service runtime
// still compiles.
//
// The check `synqt check` runs is what makes by-name safe: an entity behind a front
// carries exactly the members the front offers its callers, no more and no fewer.
QMetaMethod synqtMethodNamed(const QMetaObject *metaObject, const char *name,
                             QMetaMethod::MethodType wanted)
{
    // Most derived first, so a Replica's own member wins over anything a base declares.
    for (int index{metaObject->methodCount() - 1}; index >= 0; --index) {
        const QMetaMethod method{metaObject->method(index)};
        if (method.methodType() == wanted && method.name() == name) {
            return method;
        }
    }
    return QMetaMethod{};
}
"""

#: The same opening, for a file whose contracts raise no signal: nothing looks a method up
#: by name, so the helper that does would be an unused function.
RELAY_INTRO_ONLY = RELAY_INTRO.split("QMetaMethod synqtMethodNamed")[0]

RELAY_FOLLOW_PROPERTY = """
// Follow `name` on `replica`, calling `slot` on `source` whenever it changes and once now,
// so a Replica that already holds a value is not waited on for a second one.
bool synqtFollowProperty(QObject *replica, QObject *source, const char *name,
                         const char *slot)
{
    const int index{replica->metaObject()->indexOfProperty(name)};
    const int slotIndex{source->metaObject()->indexOfSlot(slot)};
    if (index < 0 || slotIndex < 0) {
        return false;
    }
    const QMetaProperty property{replica->metaObject()->property(index)};
    const QMetaMethod target{source->metaObject()->method(slotIndex)};
    if (property.hasNotifySignal()) {
        QObject::connect(replica, property.notifySignal(), source, target,
                         Qt::UniqueConnection);
    }
    target.invoke(source, Qt::DirectConnection);
    return true;
}
"""

RELAY_TAKES_SESSION = """
// Does the entity behind the front take the session on every call?
//
// A connect point a service consumes carries the session the calling entity is acting for,
// as one parameter ahead of the declared ones, and a point only a browser consumes carries
// nothing extra. Which of the two is behind a given front is a fact about how that point
// was compiled, so it is read off the method rather than assumed: one parameter more than
// the contract declares means the session is one of them.
bool synqtTakesSession(const QObject *replica, const char *name, int declared)
{
    const QMetaMethod method{synqtMethodNamed(replica->metaObject(), name,
                                              QMetaMethod::Slot)};
    return method.isValid() && method.parameterCount() == declared + 1;
}
"""

RELAY_FOLLOW_SIGNAL = """
// Relay a signal the entity behind the front raises out to the caller, through the
// helper's own emit<Signal>, so it passes the same bound checks and the same scope gate as
// one the front raised itself.
bool synqtFollowSignal(QObject *replica, QObject *source, const char *name, const char *slot)
{
    const QMetaMethod signal{synqtMethodNamed(replica->metaObject(), name,
                                              QMetaMethod::Signal)};
    const QMetaMethod target{synqtMethodNamed(source->metaObject(), slot,
                                              QMetaMethod::Slot)};
    if (!signal.isValid() || !target.isValid()) {
        return false;
    }
    return static_cast<bool>(QObject::connect(replica, signal, source, target,
                                              Qt::UniqueConnection));
}
"""

RELAY_ROWS = """
// The rows a model replica is holding, in the shape a Source publishes. Read through the
// model's own role names, which are the contract's declared roles and nothing else.
QVariantList synqtRowsOf(const QAbstractItemModel *model)
{
    QVariantList rows;
    if (!model) {
        return rows;
    }
    const QHash<int, QByteArray> names{model->roleNames()};
    const int count{model->rowCount()};
    rows.reserve(count);
    for (int row{0}; row < count; ++row) {
        const QModelIndex at{model->index(row, 0)};
        QVariantMap fields;
        for (auto role{names.constBegin()}; role != names.constEnd(); ++role) {
            fields.insert(QString::fromUtf8(role.value()), model->data(at, role.key()));
        }
        rows.append(fields);
    }
    return rows;
}

"""

RELAY_CLOSE = """} // namespace
"""


def emit_source_helper_source(syn: SynFile, lstem: str) -> str:
    out: List[str] = [SPDX_CPP,
                      f'#include "{lstem}_sourcehelper.h"', "",
                      "#include <QAbstractItemModel>",
                      "#include <QHash>",
                      "#include <QMetaMethod>",
                      "#include <QMetaProperty>",
                      "#include <QQmlEngine>",
                      "#include <QQmlListProperty>",
                      "#include <QVariant>",
                      "#include <QVariantList>",
                      "#include <QVariantMap>", ""]
    if _has_models(syn):
        out += ["#include <QMetaType>",
                "#include <QStandardItem>", "",
                "#include <utility>", ""]
    if _bounds_a_var(syn):
        out += ["#include <QByteArray>",
                "#include <QDataStream>",
                "#include <QIODevice>", ""]
    # Present whenever a service runtime is linked, absent for a contract-only target; the
    # registration below is guarded the same way.
    out += ["#if __has_include(<sourcefactory.h>)",
            "#  include <sourcefactory.h>",
            "#endif", ""]
    out += [MODULE_IMPORTS_INCLUDE, ""]
    if any(contract.slots for contract in syn.contracts):
        out += [ACTING_FOR_SHIM, ""]
        out += [CALL_SPAN_SHIM, ""]
    if _bounds_a_var(syn):
        out += [VARIANT_BYTES_HELPER, ""]
    has_slots = any(contract.slots for contract in syn.contracts)
    if has_slots:
        out += [SLOT_DISPATCH_HELPER, ""]
    # Only the pieces this file's contracts actually call: an unused static function in an
    # anonymous namespace is a warning, and the build treats warnings as errors.
    follows = any(contract.props or contract.models for contract in syn.contracts)
    relays_signal = any(contract.signals for contract in syn.contracts)
    relays_slot = any(contract.slots for contract in syn.contracts)
    if follows or relays_signal or relays_slot:
        needs_lookup = relays_signal or relays_slot
        relay: List[str] = [RELAY_INTRO if needs_lookup else RELAY_INTRO_ONLY]
        if relays_slot:
            relay.append(RELAY_TAKES_SESSION)
        if follows:
            relay.append(RELAY_FOLLOW_PROPERTY)
        if relays_signal:
            relay.append(RELAY_FOLLOW_SIGNAL)
        if _has_models(syn):
            relay.append(RELAY_ROWS)
        relay.append(RELAY_CLOSE)
        out += ["".join(relay), ""]
    records = syn.record_names
    path = f"{syn.stem}.syn"
    for contract in syn.contracts:
        out.append(_source_helper_impl(syn, contract, records, path))
        out.append("")

    out.append(f"void synqtRegister{_cap(syn.stem)}Sources()")
    out.append("{")
    out.append(MODULE_IMPORTS_CALL)
    for contract in syn.contracts:
        out.append(
            f'    qmlRegisterType<{contract.name}SourceHelper>("SynQt", 1, 0, "{contract.name}");'
        )
    # Install the typed Caller factory when the service runtime is present (same guard as the
    # subclass in the header), so forUser/forEntity mint the <Contract>Caller for this
    # contract and QML gets Caller.emit<Signal>(...).
    caller_contracts = [contract for contract in syn.contracts if contract.signals]
    if caller_contracts:
        out.append("#if __has_include(<caller.h>)")
        for contract in caller_contracts:
            out.append(
                f'    SynQt::Caller::registerCallerFactory(QStringLiteral("{contract.name}"),'
            )
            out.append(
                f"        [](QObject *parent) -> SynQt::Caller * "
                f"{{ return new {contract.name}Caller{{parent}}; }});"
            )
        out.append("#endif")
    # The mirror factory, on the same terms. A shared entity's runtime has to build one more
    # instance of this Source per caller and knows only the contract's name, so the one place
    # that knows the type registers a way to make one.
    out.append("#if __has_include(<sourcefactory.h>)")
    for contract in syn.contracts:
        out.append(
            f'    SynQt::SourceFactory::registerSource(QStringLiteral("{contract.name}"),'
        )
        out.append(
            f"        [](QObject *parent) -> QObject * "
            f"{{ return new {contract.name}SourceHelper{{parent}}; }});"
        )
    out.append("#endif")
    out.append("}")
    out.append("")
    return "\n".join(out)


def _source_helper_impl(syn: SynFile, contract: Contract, records, path) -> str:
    name = contract.name
    lines: List[str] = []

    lines.append(f"{name}SourceHelper::{name}SourceHelper(QObject *parent)")
    lines.append(f"    : {name}SimpleSource{{parent}}")
    lines.append("{")
    for model in contract.models:
        # An empty model, published now rather than on the owner's first set<Model>().
        # It has to be published from the constructor: enableRemoting() reads the model
        # off the Source as it registers it, and a Source that hands over a null model
        # there never gets one afterwards. The argument is spelled out because the
        # inherited set<Model>(QAbstractItemModel *) is an overload of this name too,
        # and `{}` would be a null pointer to it.
        lines.append(f"    set{_cap(model.name)}(QVariantList{{}});")
    lines.append("}")
    lines.append("")

    # The default child list: accept non-visual QML children declared in the Source. The
    # QML engine still calls componentComplete on each (so a child Timer with running:true
    # starts), independent of this object not being a visual parent.
    lines.append(f"QQmlListProperty<QObject> {name}SourceHelper::data()")
    lines.append("{")
    lines.append("    return QQmlListProperty<QObject>{this, nullptr,")
    lines.append(f"                                     &{name}SourceHelper::appendData,")
    lines.append("                                     nullptr, nullptr, nullptr};")
    lines.append("}")
    lines.append("")
    lines.append(f"void {name}SourceHelper::appendData(QQmlListProperty<QObject> *list,")
    lines.append("                                    QObject *object)")
    lines.append("{")
    lines.append("    if (!object) {")
    lines.append("        return;")
    lines.append("    }")
    lines.append(f"    {name}SourceHelper *self{{qobject_cast<{name}SourceHelper *>(list->object)}};")
    lines.append("    if (!self) {")
    lines.append("        return;")
    lines.append("    }")
    lines.append("    object->setParent(self);")
    lines.append("    self->m_data.append(object);")
    lines.append("}")
    lines.append("")

    lines.append(_mirror_impl(contract, records, path))
    lines.append("")

    lines.append(_relay_impl(contract, records, path))
    lines.append("")

    lines.append(_gate_impl(contract, records, path))
    lines.append("")

    for prop in _intercepted_props(contract):
        lines.append(_bounded_prop_impl(name, prop, records, path))
        lines.append("")

    for model in contract.models:
        lines.append(_set_model_impl(name, model, records, path))
        lines.append("")

    for slot in contract.slots:
        lines.append(_slot_impl(syn, name, slot, records, path))
    if contract.slots:
        lines.append("")

    for signal in contract.signals:
        lines.append(_emit_signal_impl(name, signal, records, path))
        lines.append("")

    return "\n".join(lines).rstrip("\n")


def _mirror_impl(contract: Contract, records, path) -> str:
    """The three methods that make one Source answerable to many callers.

    A shared entity keeps one Source and hands each caller a mirror of it. Everything the
    shared Source pushes is copied outward as it changes, so every mirror shows the same
    values; everything a caller asks for is forwarded back with that caller bound, so the
    shared Source's slots still see a Caller and can still refuse one. A signal the shared
    Source raises reaches every mirror (it is the whole point of sharing), while
    `Caller.emit<Signal>` runs on the one mirror the caller acquired and reaches them
    alone.
    """
    name = contract.name
    helper = f"{name}SourceHelper"
    gated = _is_gated(contract)
    lines = [
        f"void {helper}::synqtSetCaller(QObject *caller)",
        "{",
        "    m_synqtCaller = caller;",
    ]
    if gated:
        lines += [
            "    if (caller) {",
            "        // A scope this caller gains or loses changes what they may see, so the",
            "        // gated members are published again when it moves. String-based, like",
            "        // everything else this reaches on the Caller, so no runtime type is",
            "        // needed here. Unique, because binding a caller twice is allowed.",
            "        connect(caller, SIGNAL(scopeChanged()), this, SLOT(synqtRegate()),",
            "                Qt::UniqueConnection);",
            "    }",
            "    // What the owner assigned before there was a caller to weigh it against was",
            "    // held back; now there is one.",
            "    synqtRegate();",
        ]
    lines += [
        "}",
        "",
        f"void {helper}::synqtAdoptCaller(QObject *caller)",
        "{",
        "    // By name, so a contract target that links no service runtime still compiles:",
        "    // SynQt::Caller::adopt takes this caller's identity and the mirror it answers",
        "    // through, which is what makes one shared Source able to tell its callers apart.",
        "    if (m_synqtCaller && caller && m_synqtCaller != caller) {",
        '        QMetaObject::invokeMethod(m_synqtCaller.data(), "adopt", Qt::DirectConnection,',
        "                                  Q_ARG(QObject *, caller));",
        "    }",
        "}",
        "",
        f"void {helper}::synqtMirror(QObject *shared)",
        "{",
        f"    {helper} *source{{qobject_cast<{helper} *>(shared)}};",
        "    if (!source || source == this) {",
        "        return;",
        "    }",
        "    m_synqtShared = source;",
    ]
    if contract.props:
        lines.append("")
        lines.append("    // Pushed state: taken as it stands, then followed.")
        for prop in contract.props:
            cap = _cap(prop.name)
            lines.append(f"    set{cap}(source->{prop.name}());")
            lines.append(f"    connect(source, &{name}Source::{prop.name}Changed, this,")
            lines.append(f"            &{name}SimpleSource::set{cap});")
    if contract.models:
        lines.append("")
        lines.append("    // Rows: republished from the shared Source's last publish, which")
        lines.append("    // already dropped everything the contract does not declare.")
        for model in contract.models:
            cap = _cap(model.name)
            lines.append(f"    set{cap}(source->{model.name}Rows());")
            lines.append(f"    connect(source, &{helper}::{model.name}RowsChanged, this,")
            lines.append(f"            [this, source]() {{ set{cap}(source->{model.name}Rows()); }});")
    if contract.signals:
        lines.append("")
        lines.append("    // A signal the shared Source raises is everyone's, so every mirror")
        lines.append("    // raises it too. One addressed to a single caller is emitted on that")
        lines.append("    // caller's mirror instead and never comes through here.")
        lines.append("    // Relayed into emit<Signal> rather than straight out, so a broadcast")
        lines.append("    // passes the same bound checks and the same scope gate as one sent")
        lines.append("    // to a single caller.")
        for signal in contract.signals:
            lines.append(f"    connect(source, &{name}Source::{signal.name}, this,")
            lines.append(f"            &{helper}::emit{_cap(signal.name)});")
    lines.append("}")
    return "\n".join(lines)


def _bounded_props(contract: Contract):
    """The contract's props that were written with a bound, in declaration order."""
    return [prop for prop in contract.props if bound_of(prop.type) is not None]


def _intercepted_props(contract: Contract):
    """The props whose setter the helper overrides: bounded, gated, or both.

    Both reasons want the same hook, the virtual setter repc generates, so one override
    carries them: the bound is checked on the way in and the gate on the way out.
    """
    return [prop for prop in contract.props
            if bound_of(prop.type) is not None or _gate(prop)]


def _relay_impl(contract: Contract, records, path) -> str:
    """`synqtRelay`, and the pull slot behind each followed member.

    A front's Source answers one caller and holds nothing of its own: what it publishes is
    whatever the entity behind it is holding, and what it is asked for is forwarded there.
    Following is one-way by construction, because a Replica is read-only to its consumer,
    which is what keeps this from being a second place state can be written.
    """
    name = contract.name
    helper = f"{name}SourceHelper"
    lines = [
        f"void {helper}::synqtRelay(QObject *replica)",
        "{",
        "    m_synqtRelay = replica;",
        "    if (!replica) {",
        "        return;",
        "    }",
    ]
    for prop in contract.props:
        lines.append(f'    synqtFollowProperty(replica, this, "{prop.name}",')
        lines.append(f'                        "synqtPull{_cap(prop.name)}()");')
    for model in contract.models:
        lines.append(f'    synqtFollowProperty(replica, this, "{model.name}",')
        lines.append(f'                        "synqtPull{_cap(model.name)}()");')
    for signal in contract.signals:
        lines.append(f'    synqtFollowSignal(replica, this, "{signal.name}",')
        lines.append(f'                      "emit{_cap(signal.name)}");')
    if contract.slots:
        first = contract.slots[0]
        lines.append("    // A contract carries the session on every slot or on none, so one")
        lines.append("    // answers for all of them.")
        lines.append(f'    m_synqtRelayTakesSession = synqtTakesSession(replica, "{first.name}",')
        lines.append(f"                                                {len(first.params)});")
    lines.append("}")

    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines += [
            "",
            f"void {helper}::synqtPull{_cap(prop.name)}()",
            "{",
            "    if (!m_synqtRelay) {",
            "        return;",
            "    }",
            f'    set{_cap(prop.name)}(qvariant_cast<{ctype}>(',
            f'        m_synqtRelay->property("{prop.name}")));',
            "}",
        ]
    for model in contract.models:
        cap = _cap(model.name)
        lines += [
            "",
            f"void {helper}::synqtPull{cap}()",
            "{",
            "    if (!m_synqtRelay) {",
            "        return;",
            "    }",
            "    QAbstractItemModel *rows{",
            f'        m_synqtRelay->property("{model.name}")'
            ".value<QAbstractItemModel *>()};",
            "    if (!rows) {",
            f"        set{cap}(QVariantList{{}});",
            "        return;",
            "    }",
            "    // The property changes once, when the Replica initializes; everything after",
            "    // that is the model's own doing, so this follows the model directly. Unique,",
            "    // because this runs again on every one of those changes.",
        ]
        for signal in ("modelReset", "rowsInserted", "rowsRemoved", "rowsMoved",
                       "dataChanged", "layoutChanged"):
            lines += [
                f"    connect(rows, &QAbstractItemModel::{signal}, this,",
                f"            &{helper}::synqtPull{cap}, Qt::UniqueConnection);",
            ]
        lines += [
            f"    set{cap}(synqtRowsOf(rows));",
            "}",
        ]
    return "\n".join(lines)


def _gate_impl(contract: Contract, records, path) -> str:
    """The three methods behind a `<scope>` gate: ask, exempt, and publish again.

    `synqtAllows` reaches SynQt::Caller::hasScope by name, the way everything else here
    reaches the runtime, so a target that links no service runtime still compiles. It
    answers false when there is no caller, which is what makes an ungated shared Source
    have to say so rather than get the answer by accident.

    `synqtRegate` runs when the caller's scope changes. Every gated member is published
    again from what the owner last assigned, so one that has come into reach appears with
    its current value, and one that has gone out of reach is withdrawn rather than left
    sitting in the consumer's replica.
    """
    name = contract.name
    helper = f"{name}SourceHelper"
    lines: List[str] = []
    if _is_gated(contract):
        lines += [
        f"bool {helper}::synqtAllows(const QStringList &scopes) const",
        "{",
        "    if (m_synqtUngated || scopes.isEmpty()) {",
        "        return true;",
        "    }",
        "    if (m_synqtCaller.isNull()) {",
        "        return false;",
        "    }",
        "    for (const QString &scope : scopes) {",
        "        bool granted{false};",
        '        QMetaObject::invokeMethod(m_synqtCaller.data(), "hasScope",',
        "                                  Qt::DirectConnection, Q_RETURN_ARG(bool, granted),",
        "                                  Q_ARG(QString, scope));",
        "        if (granted) {",
        "            return true;",
        "        }",
        "    }",
        "    return false;",
        "}",
        "",
        ]
    lines += [
        f"void {helper}::synqtHoldsSharedState()",
        "{",
        "    // The one Source a shared entity answers everyone from. It holds every value",
        "    // for every caller, and the mirrors are where each caller's gate is applied.",
        "    m_synqtUngated = true;",
        "    synqtRegate();",
        "}",
        "",
        f"void {helper}::synqtRegate()",
        "{",
    ]
    body: List[str] = []
    for prop in _gated_props(contract):
        # Through the setter, which is the one place the gate is written down.
        body.append(f"    set{_cap(prop.name)}(m_synqt{_cap(prop.name)});")
    for model in contract.models:
        if _gate(model):
            body.append(f"    set{_cap(model.name)}(m_{model.name}Rows);")
    if not body:
        # Only slots and signals are gated, and neither holds anything to republish.
        body.append("")
    lines += body
    lines.append("}")
    return "\n".join(lines)


def _bounded_prop_impl(class_name: str, prop, records, path) -> str:
    """The setter that keeps a bounded prop inside its bound.

    repc makes every property setter virtual, so overriding it is the whole of the
    interception: the owner assigns in QML as usual, and a value that breaks the bound
    never reaches the member the Source pushes from.
    """
    ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
    helper = f"{class_name}SourceHelper"
    where = f"{class_name}.{prop.name}"
    lines = _bound_guard(prop.type, prop.name, where, prop.name, ["return;"], "    ")
    gate = _gate(prop)
    if gate:
        # Remembered whether or not it may be published: the assignment is the owner's, and
        # a gate that opens later publishes this, while one that closes puts the default
        # back so the value stops being on the wire the moment the scope goes.
        lines += [
            f"    m_synqt{_cap(prop.name)} = {prop.name};",
            f"    if (!synqtAllows({_gate_literal(gate)})) {{",
            f"        {class_name}SimpleSource::set{_cap(prop.name)}({ctype}{{}});",
            "        return;",
            "    }",
        ]
    lines.append(f"    {class_name}SimpleSource::set{_cap(prop.name)}({prop.name});")
    body = "\n".join(lines)
    return f"void {helper}::set{_cap(prop.name)}({ctype} {prop.name})\n{{\n{body}\n}}"


def _emit_signal_impl(class_name: str, signal: Signal, records, path) -> str:
    params = _param_list(signal.params, records, path)
    args = ", ".join(p.name for p in signal.params)
    # The owner is the one raising this, but a bound is a statement about what crosses the
    # link, not about who wrote the value: an over-long reason string is refused on the way
    # out too, so a consumer never receives something the contract says cannot arrive.
    # Caller.emit<Signal>(...) lands here as well, so one guard covers both ways of sending.
    where = f"{class_name}.{signal.name}"
    lines: List[str] = []
    gate = _gate(signal)
    if gate:
        # Every way of raising this comes through here, the shared Source's broadcast
        # included (the mirror relays it into this method), so one check covers them all.
        lines += [
            f"    if (!synqtAllows({_gate_literal(gate)})) {{",
            "        return;",
            "    }",
        ]
    for param in signal.params:
        lines += _bound_guard(param.type, param.name, where, param.name, ["return;"], "    ")
    lines.append(f"    Q_EMIT {signal.name}({args});")
    body = "\n".join(lines)
    return "\n".join([
        f"void {class_name}SourceHelper::emit{_cap(signal.name)}({params})",
        "{",
        body,
        "}",
    ])


def _set_model_impl(class_name: str, model: Model, records, path) -> str:
    roles = model.roles
    role_array = ", ".join(f'QByteArrayLiteral("{role.name}")' for role in roles)
    lines = [
        f"void {class_name}SourceHelper::set{_cap(model.name)}(const QVariantList &rows)",
        "{",
        f"    static const QList<QByteArray> declaredRoles{{{role_array}}};",
    ]
    gate = _gate(model)
    if gate:
        # Remembered before the gate rather than after the commit, because these rows are
        # what synqtRegate publishes if the scope arrives later. Denied, the model is
        # emptied rather than left alone: clearing it is what takes the rows a consumer
        # already has back off them.
        lines += [
            f"    m_{model.name}Rows = rows;",
            f"    if (!synqtAllows({_gate_literal(gate)})) {{",
            f"        m_{model.name}Model.clear();",
            f"        {class_name}SimpleSource::set{_cap(model.name)}(&m_{model.name}Model);",
            f"        Q_EMIT {model.name}RowsChanged();",
            "        return;",
            "    }",
        ]
    lines += [
        "    // Built first and committed at the end: a row that does not match the",
        "    // contract refuses the whole publish, rather than leaving half of one.",
        "    QList<QStandardItem *> items;",
        "    items.reserve(rows.size());",
        "    for (qsizetype rowIndex{0}; rowIndex < rows.size(); ++rowIndex) {",
        "        const QVariantMap row{rows.at(rowIndex).toMap()};",
        "        QStandardItem *item{new QStandardItem{}};",
        "        items.append(item);",
    ]
    for index, role in enumerate(roles):
        lines.append("")
        lines += _role_conversion(class_name, model, role, index, records, path)
    lines += [
        "    }",
        f"    m_{model.name}Model.clear();",
        "    QHash<int, QByteArray> roleNames;",
        "    for (int roleIndex{0}; roleIndex < declaredRoles.size(); ++roleIndex) {",
        "        roleNames.insert(Qt::UserRole + roleIndex, declaredRoles.at(roleIndex));",
        "    }",
        f"    m_{model.name}Model.setItemRoleNames(roleNames);",
        "    for (QStandardItem *item : std::as_const(items)) {",
        f"        m_{model.name}Model.appendRow(item);",
        "    }",
        f"    {class_name}SimpleSource::set{_cap(model.name)}(&m_{model.name}Model);",
        # Recorded after the commit, so a refused publish (an unconvertible role above)
        # leaves the property reading what is actually on the wire.
        f"    m_{model.name}Rows = rows;",
        f"    Q_EMIT {model.name}RowsChanged();",
        "}",
    ]
    return "\n".join(lines)


def _role_conversion(class_name: str, model: Model, role, index: int, records, path) -> List[str]:
    """The lines that take one declared role off a row and put it on the item.

    Only declared roles cross, so an undeclared field on the row is dropped by never
    being read. A `var` role is stored as it arrives; any other role is converted to
    its declared type, and a value that will not convert refuses the publish.
    """
    key = f'QStringLiteral("{role.name}")'
    where = f"{class_name}.{model.name}"
    refuse = ["qDeleteAll(items);", "return;"]
    if is_generic(role.type):
        lines = [
            f"        // {role.name}: declared {role.type}, so whatever arrives is what "
            "crosses.",
            f"        const QVariant {role.name}Value{{row.value({key})}};",
        ]
        lines += _bound_guard(role.type, f"{role.name}Value", where, role.name, refuse,
                              " " * 8)
        lines.append(f"        item->setData({role.name}Value, Qt::UserRole + {index});")
        return lines
    ctype = cpp_type(role.type, records, path=path, line=role.line, col=role.col)
    lines = [
        f"        // {role.name}: declared {role.type}.",
        f"        QVariant {role.name}Value{{row.value({key})}};",
        f"        if (!{role.name}Value.isValid()) {{",
        f"            {role.name}Value = QVariant{{QMetaType::fromType<{ctype}>()}};",
        "        } else {",
    ]
    lines += [
        f"            if (!{role.name}Value.convert(QMetaType::fromType<{ctype}>())) {{",
        '                qWarning("%s row %lld: role \'%s\' is declared %s and a %s does '
        'not "',
        '                         "convert to it; the publish is refused",',
        f'                         "{where}", static_cast<long long>(rowIndex),'
        f' "{role.name}", "{role.type}",',
        f"                         row.value({key}).typeName());",
        "                qDeleteAll(items);",
        "                return;",
        "            }",
    ]
    lines += _bound_guard(role.type, f"qvariant_cast<{ctype}>({role.name}Value)", where,
                          role.name, refuse, " " * 12)
    lines += [
        "        }",
        f"        item->setData({role.name}Value, Qt::UserRole + {index});",
    ]
    return lines


def _slot_impl(syn: SynFile, class_name: str, slot: Slot, records, path) -> str:
    helper = f"{class_name}SourceHelper"
    is_void = slot.return_type is None
    ret = "void" if is_void else cpp_type(
        slot.return_type, records, path=path, line=slot.line, col=slot.col)
    params = _slot_params(syn, slot, records, path)
    head = f"{ret} {helper}::{slot.name}({params})"

    # The owner implements the slot as a QML `function`, whose parameters are untyped
    # (QVariant) and whose return is a QVariant. Marshal every argument as a QVariant so
    # the invoke matches the QML method's signature, and convert a return back to its
    # declared C++ type. (Passing Q_ARG(<cppType>, ...) would silently fail to match.)
    arg_terms = [
        f"Q_ARG(QVariant, QVariant::fromValue({p.name}))" for p in slot.params
    ]
    arg_suffix = ("".join(", " + term for term in arg_terms))

    # Checked before the owner's QML ever sees the call: a bound in the contract is a rule
    # about what a caller may send, so an over-long argument is refused here rather than
    # handed on to be stored, echoed, or written to a column that is exactly that wide.
    where = f"{class_name}.{slot.name}"
    refuse = ["return;"] if is_void else [f"return {ret}{{}};"]

    # Opened before anything else and closed by its destructor, so every way out of this
    # body is timed: the two refusals below, the relay, the shared Source, the owner's QML.
    lines: List[str] = [
        f'    SynqtCallSpan synqtSpan{{"{class_name}", "{slot.name}",',
        f"                            m_synqtCaller.data(), {len(slot.params)}}};",
    ]
    if syn.forwards_session:
        # Who the calling entity says it is acting for, taken before anything else so that
        # every check below already sees the right Caller. Sent on every call, an empty one
        # included, so a Caller reused by the next call never keeps the last one's session.
        # A browser's Caller ignores it outright; see SynQt::Caller::assumeSession.
        lines += [
            "    if (m_synqtCaller) {",
            '        QMetaObject::invokeMethod(m_synqtCaller.data(), "assumeSession",',
            "                                  Qt::DirectConnection,",
            f"                                  Q_ARG(QVariantMap, {SESSION_ARG}));",
            "    }",
        ]
    gate = _gate(slot)
    if gate:
        # After the session a mesh caller is acting for is taken above, so the scope this
        # asks about is the one the call is really being made under. Refused here, before
        # the owner's QML is reached and before any argument is even looked at.
        lines += [
            f"    if (!synqtAllows({_gate_literal(gate)})) {{",
            f'        qWarning("%s: refused, the caller does not hold the scope it needs",',
            f'                 "{where}");',
            '        synqtSpan.refuse("scope");',
        ] + [f"        {line}" for line in refuse] + ["    }"]
    # A refusal is what an operator wants to be told about, so each one names which check
    # made it rather than leaving them all looking alike in the record.
    refuse_bound = ['synqtSpan.refuse("bound");'] + refuse
    for param in slot.params:
        lines += _bound_guard(param.type, param.name, where, param.name, refuse_bound, "    ")
    # Whoever this slot is answering, for as long as it runs: a call the owner's
    # implementation makes on to another entity carries them, so the chain keeps its person.
    lines.append(f"    const SynqtActingFor synqtActing{{m_synqtCaller.data()}};")
    # A front implements nothing: the call belongs to the entity serving this caller's
    # scope. Sent with the session this Source is answering for, which is what lets that
    # entity authorize the person rather than the edge that carried them.
    session_arg = "Q_ARG(QVariantMap, synqtActingForSession())"
    relay_args = "".join(
        ",\n                                  Q_ARG(%s, %s)"
        % (cpp_type(param.type, records, path=path, line=param.line, col=param.col),
           param.name)
        for param in slot.params)
    plain_args = relay_args.lstrip(",\n ")
    lines += [
        "    if (m_synqtRelay) {",
        "        if (m_synqtRelayTakesSession) {",
        f'            QMetaObject::invokeMethod(m_synqtRelay.data(), "{slot.name}",',
        f"                                      {session_arg}{relay_args});",
        "        } else {",
        f'            QMetaObject::invokeMethod(m_synqtRelay.data(), "{slot.name}"'
        + (f",\n                                      {plain_args});" if slot.params else ");"),
        "        }",
    ] + [f"        {line}" for line in refuse] + ["    }"]
    # A mirror of a shared Source answers nothing itself: it binds its caller and hands the
    # call to the Source everybody shares, which is where the slot is implemented.
    forward = f"m_synqtShared->{slot.name}({_slot_args(syn, slot)})"
    lines += [
        "    if (m_synqtShared) {",
        "        m_synqtShared->synqtAdoptCaller(m_synqtCaller);",
        f"        {'return ' if not is_void else ''}{forward};",
    ]
    if is_void:
        lines.append("        return;")
    lines.append("    }")
    lines += [
        f'    const int index{{synqtQmlSlotIndex(this, "{slot.name}", {len(slot.params)},',
        f"                                     {helper}::staticMetaObject.methodCount())}};",
    ]
    if is_void:
        lines += [
            "    if (index >= 0) {",
            f"        metaObject()->method(index).invoke(this, Qt::DirectConnection{arg_suffix});",
            "    }",
        ]
    else:
        lines += [
            "    QVariant result{};",
            "    if (index >= 0) {",
            "        metaObject()->method(index).invoke(this, Qt::DirectConnection,",
            f"                                           Q_RETURN_ARG(QVariant, result){arg_suffix});",
            "    }",
            f"    return qvariant_cast<{ret}>(result);",
        ]
    body = "\n".join(lines)
    return f"{head}\n{{\n{body}\n}}"


# consumer side
#
# The consumer facade is what the accessor family (Server, Database, ...) exposes for a
# consumed connect point: it forwards the Replica's push properties, models and signals,
# turns a returning slot into a Promise (`slot(args).then(...)`), and publishes itself to
# the ConnectPointResolver so `<Contract>.on<Signal>` attached handlers find it. It is
# Replica-type agnostic (it reflects through the metaobject), so one facade serves a typed
# Replica on the client and a dynamic Replica on the mesh. Everything is guarded on the
# runtime's <consumerbase.h>, so a Replica-only target compiles it away to nothing.


def _types_csv(params, records, path) -> str:
    return ",".join(
        cpp_type(param.type, records, path=path, line=param.line, col=param.col)
        for param in params
    )


def _qarg_suffix(params, records, path) -> str:
    terms = [
        "Q_ARG(%s, %s)"
        % (cpp_type(param.type, records, path=path, line=param.line, col=param.col), param.name)
        for param in params
    ]
    return "".join(", " + term for term in terms)


def emit_consumer_header(syn: SynFile, lstem: str) -> str:
    out: List[str] = [SPDX_CPP, "#pragma once", ""]
    out += ["#if __has_include(<consumerbase.h>)",
            "#  include <consumerbase.h>",
            "#  include <promise.h>", "",
            f'#  include "{lstem}_rep.h"', "",
            "#  include <readonlymodel.h>", "",
            "#  include <QtQml/qqmlregistration.h>", "",
            "#  include <QAbstractItemModel>",
            "#  include <QList>",
            "#  include <QObject>",
            "#  include <QString>", ""]
    records = syn.record_names
    path = f"{syn.stem}.syn"
    for contract in syn.contracts:
        out.append(_consumer_class(contract, records, path))
        out.append("")
    out.append("#endif")
    out.append("")
    out.append(f"void synqtRegister{_cap(syn.stem)}Consumers();")
    out.append("")
    return "\n".join(out)


def _consumer_class(contract: Contract, records, path) -> str:
    name = contract.name
    lines = [
        f"// Consumer facade for {name}: what `{name}` is, in the QML of an entity that",
        f"// consumes {name}'s connect point. One object serves all three ways a consumer",
        f"// reaches it, because it is the attached object for the QML type `{name}` as well",
        f"// as the accessor: `{name}.doThing()`, a binding on `{name}.someProp`, and",
        f"// `{name}.onSomeSignal:` all resolve here.",
        f"class {name}Consumer : public SynQt::ConsumerBase",
        "{",
        "    Q_OBJECT",
        f"    QML_ATTACHED({name}Consumer)",
        "    Q_PROPERTY(bool ready READ isReady NOTIFY readyChanged)",
    ]
    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines.append(
            f"    Q_PROPERTY({ctype} {prop.name} READ {prop.name} NOTIFY {prop.name}Changed)")
    for model in contract.models:
        lines.append(
            f"    Q_PROPERTY(QAbstractItemModel *{model.name} READ {model.name} "
            f"NOTIFY {model.name}Changed)")
    lines += [
        "",
        "public:",
        f"    explicit {name}Consumer(QObject *parent = nullptr);",
        "",
        "    QString contractName() const override;",
        "",
        f"    // The live facade, not a new object: `{name}` in QML has to be the one",
        "    // accessor the runtime installed, or a call would reach nothing.",
        f"    static {name}Consumer *qmlAttachedProperties(QObject *object);",
        "",
    ]
    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines.append(f"    {ctype} {prop.name}() const;")
    for model in contract.models:
        lines.append(f"    QAbstractItemModel *{model.name}() const;")
    if contract.props or contract.models:
        lines.append("")
    for slot in contract.slots:
        params = _param_list(slot.params, records, path)
        if slot.return_type is None:
            lines.append(f"    Q_INVOKABLE void {slot.name}({params});")
        else:
            lines.append(f"    Q_INVOKABLE SynQt::Promise *{slot.name}({params});")
    if contract.slots:
        lines.append("")
    lines.append("signals:")
    for prop in contract.props:
        lines.append(f"    void {prop.name}Changed();")
    for model in contract.models:
        lines.append(f"    void {model.name}Changed();")
    for signal in contract.signals:
        params = _param_list(signal.params, records, path)
        lines.append(f"    void {signal.name}({params});")
    lines += [
        "",
        "protected:",
        "    void bindReplica() override;",
        "    void emitAllChanged() override;",
    ]
    if contract.models:
        lines += [
            "",
            "private:",
            "    // What a consumer is handed for each published model: a read-only view of",
            "    // the Replica's, never the Replica's own (SynQt::ReadOnlyModel).",
        ]
        for model in contract.models:
            lines.append(f"    SynQt::ReadOnlyModel *m_{model.name}View{{nullptr}};")
    lines.append("};")
    return "\n".join(lines)


CONSUMER_RELAY_HELPER = """namespace {
// Relay one signal to another by signature, tolerating a Replica that does not expose it
// (a dynamic Replica has no model-changed property signal): connect only when both exist,
// so nothing warns. Returns the connection so the facade can drop it on the next rebind.
QMetaObject::Connection synqtRelay(QObject *from, const QByteArray &fromSignal,
                                   QObject *to, const QByteArray &toSignal)
{
    const QMetaObject *fromMeta{from->metaObject()};
    const QMetaObject *toMeta{to->metaObject()};
    const int fromIndex{fromMeta->indexOfSignal(
        QMetaObject::normalizedSignature(fromSignal.constData()).constData())};
    const int toIndex{toMeta->indexOfSignal(
        QMetaObject::normalizedSignature(toSignal.constData()).constData())};
    if (fromIndex < 0 || toIndex < 0) {
        return QMetaObject::Connection{};
    }
    return QObject::connect(from, fromMeta->method(fromIndex), to, toMeta->method(toIndex));
}
} // namespace
"""


def emit_consumer_source(syn: SynFile, lstem: str) -> str:
    out: List[str] = [SPDX_CPP, f'#include "{lstem}_consumer.h"', "", "#if __has_include(<consumerbase.h>)"]
    # moduleimports.h ships in the same library as consumerbase.h, so inside this guard it
    # is there: no second guard of its own.
    out += ['#  include "actingfor.h"',
            '#  include "connectpointresolver.h"',
            '#  include "consumerfactory.h"',
            '#  include "moduleimports.h"', "",
            "#  include <QJSEngine>",
            "#  include <QMetaMethod>",
            "#  include <QMetaObject>",
            "#  include <QtQml/qqmlengine.h>",
            "#  include <QtRemoteObjects/QRemoteObjectPendingReply>",
            "#  include <QVariant>", ""]
    out.append(CONSUMER_RELAY_HELPER)
    records = syn.record_names
    path = f"{syn.stem}.syn"
    for contract in syn.contracts:
        out.append(_consumer_impl(syn, contract, records, path))
        out.append("")
    out.append(f"void synqtRegister{_cap(syn.stem)}Consumers()")
    out.append("{")
    out.append("    // Registering a contract is what makes `import SynQt` enough: it brings")
    out.append("    // QtQuick with it, so a view that consumes this one is a window without a")
    out.append("    // second import line.")
    out.append("    SynQt::registerModuleImports();")
    for contract in syn.contracts:
        out.append(
            f'    SynQt::registerConsumerFactory(QStringLiteral("{contract.name}"),')
        out.append(
            f"        []() -> SynQt::ConsumerBase * {{ return new {contract.name}Consumer{{}}; }});")
        out.append(
            f'    qmlRegisterType<{contract.name}Consumer>("SynQt", 1, 0, '
            f'"{contract.name}");')
    out.append("}")
    out.append("#else")
    out.append(f"void synqtRegister{_cap(syn.stem)}Consumers() {{}}")
    out.append("#endif")
    out.append("")
    return "\n".join(out)


def _consumer_impl(syn: SynFile, contract: Contract, records, path) -> str:
    name = contract.name
    cls = f"{name}Consumer"
    built = "".join(
        f"\n    m_{model.name}View = new SynQt::ReadOnlyModel{{this}};"
        for model in contract.models)
    lines: List[str] = [
        f"{cls}::{cls}(QObject *parent)",
        f"    : SynQt::ConsumerBase{{parent}}",
        "{" + built,
        "}",
        "",
        f"QString {cls}::contractName() const",
        "{",
        f'    return QStringLiteral("{name}");',
        "}",
        "",
        f"{cls} *{cls}::qmlAttachedProperties(QObject *object)",
        "{",
        "    Q_UNUSED(object);",
        f'    QObject *facade{{SynQt::ConnectPointResolver::instance()->resolve('
        f'QStringLiteral("{name}"))}};',
        "    // Owned by the runtime that installed it and shared by every file that names",
        "    // it, so the engine must not take it or delete it with a scope object.",
        "    QQmlEngine::setObjectOwnership(facade, QQmlEngine::CppOwnership);",
        f"    return qobject_cast<{cls} *>(facade);",
        "}",
        "",
    ]

    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines += [
            f"{ctype} {cls}::{prop.name}() const",
            "{",
            "    if (m_replica == nullptr) {",
            f"        return {ctype}{{}};",
            "    }",
            f'    return qvariant_cast<{ctype}>(m_replica->property("{prop.name}"));',
            "}",
            "",
        ]

    for model in contract.models:
        lines += [
            f"QAbstractItemModel *{cls}::{model.name}() const",
            "{",
            "    if (m_replica == nullptr) {",
            "        return nullptr;",
            "    }",
            "    QAbstractItemModel *published{qobject_cast<QAbstractItemModel *>(",
            '        qvariant_cast<QObject *>(m_replica->property("' + model.name + '")))};',
            "    if (published == nullptr) {",
            "        return nullptr;",
            "    }",
            "    // Re-sourced rather than rebuilt, so a reconnect keeps the object every",
            "    // binding on this model already resolved.",
            "    if (m_" + model.name + "View->sourceModel() != published) {",
            "        m_" + model.name + "View->setSourceModel(published);",
            "    }",
            "    return m_" + model.name + "View;",
            "}",
            "",
        ]

    for slot in contract.slots:
        lines.append(_consumer_slot_impl(syn, name, slot, records, path))
        lines.append("")

    # bindReplica: (re)wire the property, model and signal relays from the Replica.
    lines += [f"void {cls}::bindReplica()", "{"]
    for prop in contract.props:
        ctype = cpp_type(prop.type, records, path=path, line=prop.line, col=prop.col)
        lines.append(
            f'    addConnection(synqtRelay(m_replica, "{prop.name}Changed({ctype})",')
        lines.append(
            f'                             this, "{prop.name}Changed()"));')
    for model in contract.models:
        lines.append(
            f'    addConnection(synqtRelay(m_replica,'
            f' "{model.name}Changed(QAbstractItemModelReplica*)",')
        lines.append(
            f'                             this, "{model.name}Changed()"));')
    for signal in contract.signals:
        types = _types_csv(signal.params, records, path)
        lines.append(
            f'    addConnection(synqtRelay(m_replica, "{signal.name}({types})",')
        lines.append(
            f'                             this, "{signal.name}({types})"));')
    if not (contract.props or contract.models or contract.signals):
        lines.append("    // No push properties, models or signals to relay.")
    lines += ["}", ""]

    lines += [f"void {cls}::emitAllChanged()", "{"]
    for prop in contract.props:
        lines.append(f"    emit {prop.name}Changed();")
    for model in contract.models:
        lines.append(f"    emit {model.name}Changed();")
    if not (contract.props or contract.models):
        lines.append("    // No push properties or models to re-notify.")
    lines.append("}")
    return "\n".join(lines)


def _consumer_slot_impl(syn: SynFile, class_name: str, slot: Slot, records, path) -> str:
    cls = f"{class_name}Consumer"
    params = _param_list(slot.params, records, path)
    qargs = _qarg_suffix(slot.params, records, path)
    if syn.forwards_session:
        # The session this entity is acting for right now, filled by the framework rather
        # than by the call site: the caller writes the arguments the contract declares, and
        # who they are answering is not one of them. Empty in a browser, which has nobody
        # else's session to be acting for.
        qargs = ", Q_ARG(QVariantMap, SynQt::ActingFor::current())" + qargs
    if slot.return_type is None:
        return "\n".join([
            f"void {cls}::{slot.name}({params})",
            "{",
            "    if (m_replica == nullptr) {",
            "        return;",
            "    }",
            f'    QMetaObject::invokeMethod(m_replica, "{slot.name}"{qargs});',
            "}",
        ])
    ret = cpp_type(slot.return_type, records, path=path, line=slot.line, col=slot.col)
    # Both a typed Replica and a dynamic Replica expose a returning slot as a meta-method
    # that returns QRemoteObjectPendingReply<T> with the concrete T, so one typed return arg
    # captures either (QRemoteObjectPendingReply<T> is-a QRemoteObjectPendingCall).
    return "\n".join([
        f"SynQt::Promise *{cls}::{slot.name}({params})",
        "{",
        "    QJSEngine *engine{qjsEngine(this)};",
        "    if (m_replica == nullptr) {",
        f'        return SynQt::Promise::rejected(QStringLiteral("the \'{class_name}\' connect '
        'point is not available"), engine, this);',
        "    }",
        f"    QRemoteObjectPendingReply<{ret}> reply;",
        f'    QMetaObject::invokeMethod(m_replica, "{slot.name}",',
        f"                              Q_RETURN_ARG(QRemoteObjectPendingReply<{ret}>,"
        f" reply){qargs});",
        "    return new SynQt::Promise{reply, engine, this};",
        "}",
    ])


# replica side


def emit_replica_header(syn: SynFile, lstem: str) -> str:
    return "\n".join([SPDX_CPP, "#pragma once", "",
                      f"void synqtRegister{_cap(syn.stem)}Replicas();", ""])


def emit_replica_source(syn: SynFile, lstem: str) -> str:
    out = [SPDX_CPP,
           f'#include "{lstem}_replica.h"', "",
           f'#include "{lstem}_rep.h"', "",
           "#include <QQmlEngine>", "",
           "// When this Replica is built into a client that links the SynQt client runtime,"
           " register a",
           "// typed-Replica factory: a compile-time Replica carries its API and so syncs"
           " reliably,",
           "// including in the browser (a dynamic Replica's API-definition exchange does"
           " not complete",
           "// under single-threaded WASM). A minimal replica-only target that does not link"
           " the",
           "// runtime simply skips this and still builds.",
           "#if __has_include(<replicaregistry.h>)",
           "#  include <QRemoteObjectNode>",
           "#  include <replicaregistry.h>",
           "#  define SYNQT_REPLICA_FACTORY 1",
           "#endif", "",
           f"void synqtRegister{_cap(syn.stem)}Replicas()",
           "{"]
    for contract in syn.contracts:
        out.append(
            f'    qmlRegisterUncreatableType<{contract.name}Replica>("SynQt", 1, 0,'
        )
        out.append(
            f'        "{contract.name}Replica",'
        )
        out.append(
            f'        QStringLiteral("{contract.name}Replica is acquired from the SynQt '
            'runtime, not constructed in QML"));'
        )
        out.append("#ifdef SYNQT_REPLICA_FACTORY")
        out.append(
            f'    SynQt::registerReplicaFactory(QStringLiteral("{contract.name}"),'
        )
        out.append(
            "        [](QRemoteObjectNode *node, const QString &connectPoint) -> QObject * {"
        )
        out.append(
            f"            return node->acquire<{contract.name}Replica>(connectPoint);"
        )
        out.append("        });")
        out.append("#endif")
    out.append("}")
    out.append("")
    return "\n".join(out)
