// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

// The custom provider path, against the real output of `synqt add provider`. The three
// skeletons compiled into this target are the scaffolder's own, generated by the run
// script; nothing here is hand written, so a skeleton that stopped compiling, stopped
// registering, or drifted from the family interface fails this test.
//
// This is the half of "writing a custom provider" that documentation cannot prove: the
// docs said "register it under a name" for a long time while no registry existed, and
// `provider.name: custom:X` resolved to nullptr in silence.

#include "cachefactory.h"
#include "documentfactory.h"
#include "icacheprovider.h"
#include "idocumentprovider.h"
#include "ipersistenceprovider.h"
#include "persistencefactory.h"
#include "providerconfig.h"
#include "providerregistry.h"

#include <QTest>

#include <memory>

using namespace SynQt;

class TestCustomProvider : public QObject
{
    Q_OBJECT

private slots:
    void scaffoldedProvidersRegisterThemselves()
    {
        // Merely linking the scaffolded file is enough: the registration runs at static
        // initialization, before any of this. If that ever needed a call from main(), the
        // scaffold would be a trap, because nothing tells the user to make it.
        QVERIFY2(ProviderRegistry::persistenceNames().contains(QStringLiteral("MyStore")),
                 qPrintable(ProviderRegistry::persistenceNames().join(QLatin1Char(','))));
        QVERIFY(ProviderRegistry::cacheNames().contains(QStringLiteral("MyCache")));
        QVERIFY(ProviderRegistry::documentNames().contains(QStringLiteral("MyDocs")));
    }

    void eachFamilyFactorySelectsItsScaffoldedProvider()
    {
        // The user-facing claim of `synqt add provider`: scaffold it, compile it into the
        // entity, select it with provider.name. No framework edit in between.
        ProviderConfig persistence;
        persistence.name = QStringLiteral("custom:MyStore");
        QString error;
        std::unique_ptr<IPersistenceProvider> store{
            makePersistenceProvider(persistence, &error)};
        QVERIFY2(store != nullptr, qPrintable(error));
        QCOMPARE(store->name(), QStringLiteral("custom:MyStore"));

        ProviderConfig cache;
        cache.name = QStringLiteral("custom:MyCache");
        std::unique_ptr<ICacheProvider> cached{makeCacheProvider(cache, &error)};
        QVERIFY2(cached != nullptr, qPrintable(error));
        QCOMPARE(cached->name(), QStringLiteral("custom:MyCache"));

        ProviderConfig document;
        document.name = QStringLiteral("custom:MyDocs");
        std::unique_ptr<IDocumentProvider> docs{makeDocumentProvider(document, &error)};
        QVERIFY2(docs != nullptr, qPrintable(error));
        QCOMPARE(docs->name(), QStringLiteral("custom:MyDocs"));
    }

    void anUnfinishedProviderFailsLoudlyRatherThanQuietly()
    {
        // The scaffold compiles before it is finished, which is deliberate: you can wire
        // the entity up first. What it must never do is look like it worked. Every
        // persistence operation reports itself unimplemented, through the interface.
        ProviderConfig config;
        config.name = QStringLiteral("custom:MyStore");
        std::unique_ptr<IPersistenceProvider> store{makePersistenceProvider(config)};
        QVERIFY(store != nullptr);

        const DbResult queried{store->query(QStringLiteral("SELECT 1"), {})};
        QVERIFY(!queried.ok);
        QVERIFY2(queried.error.contains(QStringLiteral("not implemented")),
                 qPrintable(queried.error));
        QVERIFY2(queried.error.contains(QStringLiteral("query")), qPrintable(queried.error));

        QString error;
        QVERIFY(!store->migrate(QStringList{QStringLiteral("CREATE TABLE t (id INT)")}, &error));
        QVERIFY2(error.contains(QStringLiteral("migrate")), qPrintable(error));
    }
};

QTEST_MAIN(TestCustomProvider)
#include "tst_customprovider.moc"
