// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

import QtQuick
import SynQt

// The authoritative identity Source on the auth entity (one instance per consuming
// edge, so each edge's answer reaches only that edge). It bridges the connect
// point to a single shared IdentityService (the `IdentityEngine` context object), which owns
// the client secret, the token exchange and the stored tokens. The service methods are
// synchronous, so this Source emits each result on itself and answers only the edge that
// asked; a user's identity never crosses to another edge.
//
// Generated by `synqt build` from `identity.provider_entity`; edit the topology, not this
// file.
Identity {
    id: source

    function beginLogin(requestId, provider, redirectUri, binding, context) {
        const result = IdentityEngine.beginLogin(provider, redirectUri, binding, context);
        source.emitBeginResult(requestId, result.state, result.authorizeUrl, result.error);
    }

    // The binding an edge tied this login to is held here with the state and checked here,
    // before the code is spent, so any edge process can answer a callback any other one
    // started and none of them can answer it twice.
    function exchangeCode(requestId, state, code, redirectUri, presentedBinding) {
        const result = IdentityEngine.exchangeCode(state, code, redirectUri, presentedBinding);
        source.emitExchangeResult(requestId, result.identityJson, result.context, result.error);
    }

    function bindSession(state, sessionId) {
        IdentityEngine.bindSession(state, sessionId);
    }

    function releaseSession(sessionId) {
        IdentityEngine.releaseSession(sessionId);
    }
}
