// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

import SynQt

// The authoritative identity Source on the auth entity (one instance per consuming
// edge, so each edge's answer reaches only that edge). It bridges the connect
// point to a single shared IdentityService (the `IdentityEngine` context object), which owns
// the client secret, the token exchange and the stored tokens. Every result is emitted on
// this Source, which is one edge's, so a user's identity never crosses to another edge:
// the answers that come back at once are emitted here, and the one that waits on the
// provider is handed this Source to answer when it has something to say.
//
// Generated by `synqt build` from `identity.provider_entity`; edit the topology, not this
// file.
Identity {
    id: root

    function beginLogin(requestId, provider, redirectUri, binding, context) {
        const result = IdentityEngine.beginLogin(provider, redirectUri, binding, context);
        root.emitBeginResult(requestId, result.state, result.authorizeUrl, result.error);
    }

    // The binding an edge tied this login to is held here with the state and checked here,
    // before the code is spent, so any edge process can answer a callback any other one
    // started and none of them can answer it twice.
    //
    // The engine answers later rather than returning: a slot that waited for the provider
    // put every caller that arrived meanwhile under it on the stack, and none of them
    // could be answered until the slowest one below them was. It is handed this Source and
    // the request id, so the answer reaches the one edge that asked.
    function exchangeCode(requestId, state, code, redirectUri, presentedBinding) {
        IdentityEngine.exchangeCode(state, code, redirectUri, presentedBinding,
                                    root, requestId);
    }

    function bindSession(state, sessionId) {
        IdentityEngine.bindSession(state, sessionId);
    }

    // A desktop claim is minted on whichever edge answered the callback and redeemed over a
    // connection the native client opens for itself, so it is held here where every edge
    // can reach it. An empty sessionId is every failure alike, on purpose.
    function holdClaim(code, sessionId, challenge) {
        IdentityEngine.holdClaim(code, sessionId, challenge);
    }

    function takeClaim(requestId, code, verifier) {
        root.emitClaimResult(requestId, IdentityEngine.takeClaim(code, verifier));
    }

    function releaseSession(sessionId) {
        IdentityEngine.releaseSession(sessionId);
    }
}
