#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Write the design editor's generated assets from the modules that own them.

The editor is a directory of static files with no Python behind it, and one thing it needs
is what `synqt add entity --type monitor` would have written: a console client, a sign-in
page, and the bundle map that decides who gets which. Those are the scaffolder's, not the
editor's, so the editor reads them rather than carrying a second copy that drifts.

Run this after changing anything in `synqt/monitorscaffold.py` that the editor publishes:

    python tools/gen-design-assets.py

`tools/synqt/tests/test_monitoring.py` fails when the committed file and the module
disagree, so a forgotten run is a red build rather than a page quietly serving last month's
console.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools" / "synqt"))

from synqt import monitorscaffold  # noqa: E402  (after the path is set up)

#: Every generated asset, as the path it is written to, the module-level name the editor
#: imports it under, and the function that answers it.
ASSETS = {
    Path("tools/synqt/synqt/assets/design/monitor.js"):
        ("MONITOR_SCAFFOLD", monitorscaffold.design_asset),
}

#: A module the editor imports, not a file it fetches. An `import` is resolved before any
#: of this code runs, so there is no load order to get right and no failure path where the
#: page is up and the templates are not: either the editor loaded or it did not.
_TEMPLATE = """// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

// GENERATED by tools/gen-design-assets.py. Do not edit.
//
// What `synqt add entity --type monitor` writes, published so the editor can write the
// same thing with no SynQt behind the page. The scaffolder is the one writer; this is its
// answer, and tools/synqt/tests/test_monitoring.py fails when the two disagree.

export const {name} = {payload};
"""


def rendered(name: str, payload: dict) -> str:
    """The bytes the file holds, so the writer and the drift check agree on formatting."""
    return _TEMPLATE.format(
        name=name, payload=json.dumps(payload, indent=4, sort_keys=True, ensure_ascii=True))


def main() -> int:
    for relative, (name, answer) in ASSETS.items():
        path = ROOT / relative
        text = rendered(name, answer())
        if path.exists() and path.read_text(encoding="utf-8") == text:
            print(f"unchanged  {relative}")
            continue
        path.write_text(text, encoding="utf-8")
        print(f"written    {relative}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
