#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Write SynQt's loading page over a bare Qt WebAssembly build directory.

`qt-cmake` generates a `<target>.html` from Qt's stock template: the Qt logo on the
browser's default white. That page is fine for a Qt example and wrong for every page
this project actually shows, so the raw WebAssembly spikes under `tests/` serve this
instead. The markup and the CSS come from `synqt.appgen.render_client_shell`, the same
renderer `synqt build` uses for a real app, so there is one loading page in the project
and a change to its look cannot pass the browser tests while missing the product (or the
other way round).

Only the boot differs, and only because the product's boot has more to do: a real bundle
is described by a `synqt-manifest.json` (byte counts for a true progress bar) and may be
cached by a service worker, neither of which a spike build has. The boot written here is
the same qtloader call with those two parts removed.

    tools/wasm-shell.py --target m0-client --out build/m0-client
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(_ROOT / "synqt"))

from synqt import appgen  # noqa: E402  (after the path is set up)

# Kept deliberately close to appgen's _BOOT_JS: same element ids, same qtLoad options,
# same overlay handling. What is gone is the manifest fetch (the total comes from the
# response's Content-Length here, since a spike is served uncompressed) and the service
# worker registration.
_SPIKE_BOOT_JS = """// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

// Boots the Qt WebAssembly module for a raw SynQt test spike. External and eval-free,
// like the product boot, so a page served through the edge's Content-Security-Policy
// behaves the same here. Generated by tools/wasm-shell.py; never edit in place.
(function () {
    "use strict";

    var loading = null;
    var bar = null;
    var status = null;
    var screen = null;

    function setProgress(loaded, total) {
        if (!bar || !(total > 0)) {
            return;
        }
        var percent = Math.max(0, Math.min(100, (loaded / total) * 100));
        bar.style.width = percent.toFixed(1) + "%";
        if (status) {
            status.textContent = "Loading " + percent.toFixed(0) + "%";
        }
    }

    // The chunks go straight through to compileStreaming, so counting them costs no
    // buffering and compilation still overlaps the download.
    function countingResponse(response, total) {
        if (!response.body || typeof TransformStream === "undefined") {
            return response;
        }
        var loaded = 0;
        var counter = new TransformStream({
            transform: function (chunk, controller) {
                loaded += chunk.byteLength;
                setProgress(loaded, total);
                controller.enqueue(chunk);
            }
        });
        return new Response(response.body.pipeThrough(counter), {
            headers: { "Content-Type": "application/wasm" }
        });
    }

    function compileModule() {
        return fetch("TARGET.wasm", { credentials: "same-origin" }).then(function (response) {
            if (!response.ok) {
                throw new Error("could not fetch TARGET.wasm: " + response.status);
            }
            var total = Number(response.headers.get("Content-Length") || 0);
            return WebAssembly.compileStreaming(countingResponse(response, total));
        });
    }

    function fail(error) {
        if (status) {
            status.textContent = "Failed to load";
        }
        if (loading) {
            loading.hidden = false;
        }
        console.error(error);
    }

    function init() {
        loading = document.querySelector("#synqt-loading");
        bar = document.querySelector("#synqt-bar");
        status = document.querySelector("#synqt-status");
        screen = document.querySelector("#screen");

        try {
            qtLoad({
                qt: {
                    module: compileModule(),
                    onLoaded: function () {
                        if (loading) {
                            loading.hidden = true;
                        }
                    },
                    onExit: function (exitData) {
                        var suffix = exitData.code !== undefined
                            ? " with code " + exitData.code : "";
                        if (status) {
                            status.textContent = "Application exit" + suffix;
                        }
                        if (loading) {
                            loading.hidden = false;
                        }
                    },
                    entryFunction: window.ENTRY_FUNCTION,
                    containerElements: [screen]
                }
            });
        } catch (error) {
            fail(error);
        }
    }

    window.addEventListener("load", init);
})();
"""


def render(target: str, out_dir: Path) -> None:
    """Write index.html and synqt-boot.js for `target` into `out_dir`."""
    # An empty config means every `build.loading` value falls back to its default, which
    # is the point: this is what an app that has configured nothing looks like.
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "index.html").write_text(
        appgen.render_client_shell("%s.js" % target, {}, out_dir), encoding="utf-8")
    # Emscripten turns every dash in the target name into an underscore for the entry
    # symbol (Qt's own generated page does the same).
    entry = "%s_entry" % target.replace("-", "_")
    (out_dir / "synqt-boot.js").write_text(
        _SPIKE_BOOT_JS.replace("TARGET", target).replace("ENTRY_FUNCTION", entry),
        encoding="utf-8")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--target", required=True,
                        help="The CMake target name of the WebAssembly client.")
    parser.add_argument("--out", required=True,
                        help="The build directory holding <target>.js and qtloader.js.")
    arguments = parser.parse_args(argv)

    out_dir = Path(arguments.out)
    if not (out_dir / ("%s.js" % arguments.target)).exists():
        print("wasm-shell: %s/%s.js is missing; build the client first"
              % (out_dir, arguments.target), file=sys.stderr)
        return 1
    render(arguments.target, out_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
