# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""Build the project this suite drives, with the tooling a developer would use.

Nothing here is a fixture copied into the repository. The monitor, its console client and
the sign-in gate are written by `synqt add entity <name> --type monitor` at run time, so
what the browser loads is what the scaffolder produces today and not what it produced on
the day somebody pasted it in. A console that drifts from its scaffolder is a console
nobody would notice had drifted.
"""

import sys
from pathlib import Path

import yaml

from synqt import (addentity, appgen, appmodel, check, mesh, monitorops,
                   topologywriter)

BASE = """\
# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

# Generated by tests/monitor-console/make-project.py. The monitor half is added below by
# the scaffolder, exactly as a developer would add it.
project:
  name: watched
  version: 0.1.0
  qt_version: 6.11.1

# The client's own diagnostics, on. A release WASM build is silent by default, which is
# right for something served to visitors and wrong for a suite whose whole job is to find
# out why a client did not come up.
build:
  client_logging: console

scopes:
  order: [anonymous, user]
  hierarchical: true
  default: anonymous

entities:
  - name: app
    type: client
    targets: [wasm]

  - name: web
    type: web_edge
    public:
      host: 127.0.0.1
      port: 8443

connect_points:
  - owner: web
    consumers: [app]
    export: |
      prop string[80] headline
      slot refresh()
"""

EDGE_QML = """\
// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

// The one thing this edge does, and the only reason it is here: it says something, so the
// console has an entity other than the monitor to show.
import SynQt
import QtQuick

Web {
    id: edge

    headline: "watched"

    function refresh(): void {
        Log.info("headline refreshed", { headline: edge.headline });
    }

    // Said on a timer rather than once at startup. An entity's first words are spoken
    // before its link to the monitor is up, so they reach the spool and arrive on replay;
    // this suite is about what the console shows, so it wants something said while
    // somebody is watching too.
    Timer {
        interval: 1000
        repeat: true
        running: true

        onTriggered: Log.info("still watching", { headline: edge.headline })
    }
}
"""

APP_QML = """\
// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

import SynQt
import QtQuick.Controls

ApplicationWindow {
    visible: true
    width: 320
    height: 200

    Label {
        anchors.centerIn: parent
        text: Web.headline
    }
}
"""


def main() -> int:
    root = Path(sys.argv[1])
    repo = sys.argv[2]
    root.mkdir(parents=True, exist_ok=True)
    (root / "synqt.yaml").write_text(BASE)
    (root / "web" / "web").mkdir(parents=True, exist_ok=True)
    (root / "web" / "web" / "Web.qml").write_text(EDGE_QML)
    (root / "client" / "app").mkdir(parents=True, exist_ok=True)
    (root / "client" / "app" / "Main.qml").write_text(APP_QML)

    # The whole monitoring half, from the command a developer runs. It writes the monitor,
    # the console client, the sign-in gate and `monitoring.entity`, and regenerates.
    print(addentity.scaffold(root, "ops", "monitor"))

    # The JSONL exporter, on. The suite reads the monitor's record through it rather than
    # reaching into its SQLite file, which keeps the harness to interfaces a deployment
    # actually has.
    text = (root / "synqt.yaml").read_text().replace(
        "    retention:",
        "    export:\n"
        "      jsonl:\n"
        "        path: build/ops/state/events.jsonl\n"
        "        max_bytes: 8388608\n"
        "        keep: 2\n"
        "    retention:")
    (root / "synqt.yaml").write_text(text)

    config = yaml.safe_load((root / "synqt.yaml").read_text())
    ok, messages = check.check_project(root)
    for message in messages:
        print("  synqt check:", message)
    if not ok:
        return 1

    # A real mesh, because the link the edge reports through is a real mesh link: mutual
    # TLS against a project CA, like every other. A suite that turned that off would be
    # proving the console works over a transport no deployment uses.
    # The project CA, not the throwaway development one: a resolved topology names
    # synqt/mesh/<entity>.crt, and `synqt dev` is what substitutes synqt/mesh/dev/. This
    # suite launches the binaries itself, so it issues what the topology asks for. Getting
    # that wrong is silent at run time, and `synqt check` says so out loud, which is how it
    # was caught here.
    print(mesh.init(root))
    services = [str(entity.get("name")) for entity in config["entities"]
                if not appmodel.is_client(entity)]
    print(mesh.cert_all(root, services))

    topologywriter.write(root, config)
    appgen.generate(root, config, synqt_root=repo)

    # The operator, minted the way the CLI mints one. Written to the monitor's own
    # environment file and nowhere else.
    entry = monitorops.mint("alice", "correct-horse-battery")
    env = root / "monitor" / "ops" / ".env"
    env.write_text(f"{monitorops.CREDENTIAL_VARIABLE}={entry}\n")
    print(f"  operator credential written to {env}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
