# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

"""The project this suite drives: one web edge, one client, three scopes.

Written here rather than checked in, for the same reason every other generated suite does
it: what runs is what the tooling produces today. The client is never built for the
browser, because nothing this suite proves needs it. Which bundle the edge answers with is
the whole instrument: three directories holding one line of HTML each, one per scope, so
"who is this tab" is a question a browser can be asked by loading a page.
"""

import sys
from pathlib import Path

import yaml

from synqt import appgen, check, devidentities, topologywriter

BASE = """\
# SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
# SPDX-License-Identifier: Apache-2.0

# Generated by tests/identity-picker/make-project.py.
project:
  name: picked
  version: 0.1.0
  qt_version: 6.11.1

scopes:
  order: [anonymous, user, moderator]
  hierarchical: true
  default: anonymous

entities:
  - name: app
    type: client
    targets: [wasm]

  - name: web
    type: web_edge
    public:
      host: 127.0.0.1
      port: 8443

connect_points:
  - owner: web
    consumers: [app]
    export: |
      prop string[80] headline
"""

EDGE_QML = """\
// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

import SynQt

Web {
    headline: "picked"
}
"""

APP_QML = """\
// SPDX-FileCopyrightText: 2026 Alexandre 'kidev' Poumaroux
// SPDX-License-Identifier: Apache-2.0

import SynQt
import QtQuick.Controls

ApplicationWindow {
    visible: true
    width: 320
    height: 120

    Label {
        anchors.centerIn: parent
        text: Web.headline
    }
}
"""

# One line of HTML per scope. The bundle gate is what this suite reads a session through:
# an httpOnly cookie cannot be read from a page, so "which bundle came back" is how a
# browser is asked who it is.
PAGE = """\
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>picked</title></head>
<body><h1 id="who">{scope}</h1></body>
</html>
"""

# The named half of the picker. Two entries, one of them naming a scope this project does
# not declare, so the page has to show one name and one refusal.
IDENTITIES = """\
- email: alice@example.com
  scope: moderator
- email: nobody@example.com
  scope: wizard
"""


def main() -> int:
    root = Path(sys.argv[1])
    repo = sys.argv[2]
    root.mkdir(parents=True, exist_ok=True)
    (root / "synqt.yaml").write_text(BASE)
    (root / "web" / "web").mkdir(parents=True, exist_ok=True)
    (root / "web" / "web" / "Web.qml").write_text(EDGE_QML)
    (root / "client" / "app").mkdir(parents=True, exist_ok=True)
    (root / "client" / "app" / "Main.qml").write_text(APP_QML)
    (root / devidentities.FILE_NAME).write_text(IDENTITIES)

    for scope in ("anonymous", "user", "moderator"):
        bundle = root / "bundles" / scope
        bundle.mkdir(parents=True, exist_ok=True)
        (bundle / "index.html").write_text(PAGE.format(scope=scope))

    config = yaml.safe_load((root / "synqt.yaml").read_text())
    ok, messages = check.check_project(root)
    for message in messages:
        print("  synqt check:", message)
    if not ok:
        return 1

    topologywriter.write(root, config)
    appgen.generate(root, config, synqt_root=repo)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
